[package]
name = "domain_types"
version = "0.1.0"
edition = "2021"

[dependencies]
grpc-api-types = { version = "0.1.0", path = "../grpc-api-types" }
utoipa = { version = "4.2.0", features = ["preserve_order", "preserve_path_order"] }

#third party dependencies
hyperswitch_domain_models = { path = "/Users/utkarsh.pandey/Documents/repo/hyperswitch/crates/hyperswitch_domain_models", features = ["v1"] }
thiserror = "1.0.49"
strum = { version = "0.26", features = ["derive"] }
serde = {version = "1.0.189" ,features = ["derive"]}
serde_json = "1.0.107"
error-stack = "0.4.1"
common_enums = { path = "/Users/utkarsh.pandey/Documents/repo/hyperswitch/crates/common_enums" }
cards = { path = "/Users/utkarsh.pandey/Documents/repo/hyperswitch/crates/cards" }
common_utils = { path = "/Users/utkarsh.pandey/Documents/repo/hyperswitch/crates/common_utils", features = ["async_ext", "metrics", "encryption_service", "keymanager"] }
api_models = { path = "/Users/utkarsh.pandey/Documents/repo/hyperswitch/crates/api_models", features = ["errors", "v1"] }
hyperswitch_interfaces = { path = "/Users/utkarsh.pandey/Documents/repo/hyperswitch/crates/hyperswitch_interfaces", features = ["v1"] }
masking = { path = "/Users/utkarsh.pandey/Documents/repo/hyperswitch/crates/masking" }