language: en-US
tone_instructions: ""
early_access: true
enable_free_tier: true
reviews:
  profile: chill
  request_changes_workflow: false
  high_level_summary: false
  high_level_summary_in_walkthrough: false
  auto_title_instructions: ""
  review_status: false
  commit_status: false
  fail_commit_status: false
  collapse_walkthrough: true
  changed_files_summary: true
  sequence_diagrams: false
  estimate_code_review_effort: false
  assess_linked_issues: false
  related_issues: false
  related_prs: false
  suggested_labels: false
  auto_apply_labels: false
  suggested_reviewers: false
  auto_assign_reviewers: false
  poem: false
  labeling_instructions:
    - label: ""
      instructions: ""
  path_filters: []
  path_instructions:
    - path: ""
      instructions: ""
  abort_on_close: true
  disable_cache: false
  auto_review:
    enabled: true
    auto_incremental_review: true
    ignore_title_keywords: []
    labels:
      - coderabbit-ai-review
    drafts: false
    base_branches: []
  finishing_touches:
    docstrings:
      enabled: false
    unit_tests:
      enabled: false
  tools:
    ast-grep:
      rule_dirs: []
      util_dirs: []
      essential_rules: true
      packages: []
    shellcheck:
      enabled: false
    ruff:
      enabled: false
    markdownlint:
      enabled: true
    github-checks:
      enabled: true
      timeout_ms: 90000
    languagetool:
      enabled: false
      enabled_rules: []
      disabled_rules: []
      enabled_categories: []
      disabled_categories: []
      enabled_only: false
      level: default
    biome:
      enabled: false
    hadolint:
      enabled: true
    swiftlint:
      enabled: false
      config_file: ""
    phpstan:
      enabled: false
      level: default
    golangci-lint:
      enabled: false
      config_file: ""
    yamllint:
      enabled: true
    gitleaks:
      enabled: true
    checkov:
      enabled: false
    detekt:
      enabled: false
      config_file: ""
    eslint:
      enabled: false
    flake8:
      enabled: false
    rubocop:
      enabled: false
    buf:
      enabled: true
    regal:
      enabled: false
    actionlint:
      enabled: true
    pmd:
      enabled: false
      config_file: ""
    phpmd:
      enabled: false
    phpcs:
      enabled: false
    cppcheck:
      enabled: false
    semgrep:
      enabled: true
      config_file: ""
    circleci:
      enabled: false
    clippy:
      enabled: true
    sqlfluff:
      enabled: false
    prismaLint:
      enabled: false
    pylint:
      enabled: false
    oxc:
      enabled: false
    shopifyThemeCheck:
      enabled: false
    luacheck:
      enabled: false
    brakeman:
      enabled: false
    dotenvLint:
      enabled: false
    htmlhint:
      enabled: false
    checkmake:
      enabled: false
chat:
  auto_reply: true
  integrations:
    jira:
      usage: auto
    linear:
      usage: auto
knowledge_base:
  opt_out: false
  web_search:
    enabled: true
  code_guidelines:
    enabled: true
    filePatterns: []
  learnings:
    scope: local
  issues:
    scope: local
  pull_requests:
    scope: local
code_generation:
  docstrings:
    language: en-US
    path_instructions:
      - path: ""
        instructions: ""
  unit_tests:
    path_instructions:
      - path: ""
        instructions: ""