{-# LANGUAGE OverloadedStrings #-}
{-# LANGUAGE ScopedTypeVariables #-}
{-# LANGUAGE RecordWildCards #-}

-- | High-level connector client that wraps the FFI bindings.
--
-- Handles the full round-trip for any payment flow:
--   1. Serialize protobuf request to bytes
--   2. Build connector HTTP request via 'FfiClient.callReq'
--   3. Execute the HTTP request
--   4. Parse the connector response via 'FfiClient.callRes'
--   5. Deserialize protobuf response from bytes
--
-- Flow methods (authorize, capture, void, refund, ...) are in
-- Payments.Generated.Flows, generated by the SDK codegen script.
module Payments.ConnectorClient
  ( ConnectorClient(..)
  , HttpConfig(..)
  , HttpResponse(..)
  , ConnectorError(..)
  , newConnectorClient
  , executeFlow
  , executeDirect
  , executeHttpRequest
  , defaultHttpConfig
  ) where

import qualified Data.ByteString as BS
import qualified Data.ByteString.Lazy as LBS
import qualified Data.ByteString.Char8 as BS8
import Data.Text (Text)
import qualified Data.Text as T
import qualified Data.Text.Encoding as TE
import Data.IORef
import Data.Maybe (fromMaybe)
import Control.Exception (Exception, throwIO, catch, SomeException)

import qualified Network.HTTP.Client as HTTP
import qualified Network.HTTP.Client.TLS as TLS
import qualified Network.HTTP.Types as HT

import qualified Payments.FfiClient as FFI

-- | HTTP configuration options.
data HttpConfig = HttpConfig
  { httpTotalTimeoutMs    :: !Int
  , httpConnectTimeoutMs  :: !Int
  , httpResponseTimeoutMs :: !Int
  } deriving (Show, Eq)

-- | Default HTTP configuration.
defaultHttpConfig :: HttpConfig
defaultHttpConfig = HttpConfig
  { httpTotalTimeoutMs    = 30000
  , httpConnectTimeoutMs  = 10000
  , httpResponseTimeoutMs = 30000
  }

-- | HTTP response from a connector.
data HttpResponse = HttpResponse
  { hrStatusCode :: !Int
  , hrHeaders    :: ![(BS.ByteString, BS.ByteString)]
  , hrBody       :: !BS.ByteString
  } deriving (Show)

-- | Errors from the connector client.
data ConnectorError = ConnectorError
  { ceMessage :: !Text
  , ceCode    :: !Int
  , ceContext :: !Text
  } deriving (Show, Eq)

instance Exception ConnectorError

-- | Opaque handle wrapping the FFI client and an HTTP manager.
data ConnectorClient = ConnectorClient
  { ccFfi        :: !FFI.FfiClient
  , ccConfigBytes :: !BS.ByteString  -- ^ Serialized FfiOptions protobuf
  , ccHttpConfig :: !HttpConfig
  , ccManager    :: !HTTP.Manager
  }

-- | Create a new ConnectorClient.
--
-- @configBytes@ should be protobuf-encoded FfiOptions (environment + connector auth).
-- @httpConfig@ is optional HTTP tuning.
-- @libPath@ is an optional path to the native FFI library.
newConnectorClient
  :: BS.ByteString   -- ^ Protobuf-encoded FfiOptions
  -> HttpConfig       -- ^ HTTP configuration
  -> Maybe FilePath   -- ^ Optional path to native library
  -> IO ConnectorClient
newConnectorClient configBytes httpConfig mbLibPath = do
  ffi <- FFI.newFfiClient mbLibPath
  mgr <- TLS.newTlsManager
  pure $ ConnectorClient ffi configBytes httpConfig mgr

-- | Execute a full round-trip for a payment flow.
--
-- 1. Calls the Rust req transformer via FFI to build the connector HTTP request
-- 2. Executes the HTTP request
-- 3. Calls the Rust res transformer via FFI to parse the response
--
-- Both @requestBytes@ and the return value are protobuf-encoded.
executeFlow
  :: ConnectorClient
  -> String          -- ^ Flow name (e.g. "authorize")
  -> BS.ByteString   -- ^ Protobuf-encoded request
  -> IO BS.ByteString -- ^ Protobuf-encoded response
executeFlow ConnectorClient{..} flow requestBytes = do
  -- 1. Build connector HTTP request via FFI
  connReqBytes <- FFI.callReq ccFfi flow requestBytes ccConfigBytes

  -- 2. Parse the FfiConnectorHttpRequest from protobuf bytes
  --    The bytes encode: url, method, headers map, body
  --    We use a minimal protobuf parser for the HTTP request fields.
  httpResp <- executeHttpRequest ccManager ccHttpConfig connReqBytes

  -- 3. Parse connector response via FFI
  let respBytes = encodeHttpResponse httpResp
  FFI.callRes ccFfi flow respBytes requestBytes ccConfigBytes

-- | Execute a single-step flow directly (no HTTP round-trip).
executeDirect
  :: ConnectorClient
  -> String          -- ^ Flow name (e.g. "process_webhook")
  -> BS.ByteString   -- ^ Protobuf-encoded request
  -> IO BS.ByteString -- ^ Protobuf-encoded response
executeDirect ConnectorClient{..} flow requestBytes =
  FFI.callDirect ccFfi flow requestBytes ccConfigBytes

-- | Execute an HTTP request given the protobuf-encoded FfiConnectorHttpRequest.
--
-- This is a minimal protobuf field parser for the FfiConnectorHttpRequest message.
-- Fields: url (1, string), method (2, string), headers (3, map), body (4, string).
--
-- For a production deployment the proto-lens generated types should be used.
-- This implementation allows the SDK to work without generated proto code for
-- the internal FFI types.
executeHttpRequest :: HTTP.Manager -> HttpConfig -> BS.ByteString -> IO HttpResponse
executeHttpRequest mgr config connReqBytes = do
  -- Parse URL and method from the serialized connector request.
  -- The FfiConnectorHttpRequest protobuf has fields:
  --   string url = 1; string method = 2; map<string,string> headers = 3; string body = 4;
  let fields = parseSimpleProto connReqBytes
      url    = fromMaybe "" (lookup 1 fields)
      method = fromMaybe "GET" (lookup 2 fields)
      body   = fromMaybe "" (lookup 4 fields)

  req0 <- HTTP.parseRequest (BS8.unpack url)
  let req = req0
        { HTTP.method = method
        , HTTP.requestBody = HTTP.RequestBodyBS body
        , HTTP.responseTimeout = HTTP.responseTimeoutMicro (httpResponseTimeoutMs config * 1000)
        }

  resp <- HTTP.httpLbs req mgr
  let statusCode = HT.statusCode (HTTP.responseStatus resp)
      headers    = HTTP.responseHeaders resp
      respBody   = LBS.toStrict (HTTP.responseBody resp)
      hdrs       = map (\(k, v) -> (HT.original k, v)) headers

  pure $ HttpResponse statusCode hdrs respBody

-- | Encode an HttpResponse into protobuf bytes for FfiConnectorHttpResponse.
-- Fields: int32 status_code = 1; map<string,string> headers = 2; string body = 3;
encodeHttpResponse :: HttpResponse -> BS.ByteString
encodeHttpResponse HttpResponse{..} = BS.concat $
  [ encodeVarintField 1 (fromIntegral hrStatusCode)
  , encodeBytesField 3 hrBody
  ] ++ map encodeHeader hrHeaders
  where
    encodeHeader (k, v) =
      let entry = BS.concat [encodeBytesField 1 k, encodeBytesField 2 v]
      in encodeBytesField 2 entry

-- | Minimal protobuf wire format helpers.
-- These parse/encode just enough to handle FfiConnectorHttpRequest/Response.

-- Parse length-delimited and varint fields from a protobuf message.
parseSimpleProto :: BS.ByteString -> [(Int, BS.ByteString)]
parseSimpleProto = go []
  where
    go acc bs
      | BS.null bs = acc
      | otherwise =
          let (tag, bs1) = decodeVarint bs
              fieldNum = fromIntegral (tag `div` 8) :: Int
              wireType = tag `mod` 8
          in case wireType of
               0 -> -- varint
                 let (val, bs2) = decodeVarint bs1
                 in go ((fieldNum, encodeVarintBS val) : acc) bs2
               2 -> -- length-delimited
                 let (len, bs2) = decodeVarint bs1
                     (dat, bs3) = BS.splitAt (fromIntegral len) bs2
                 in go ((fieldNum, dat) : acc) bs3
               _ -> acc  -- skip unknown wire types

    decodeVarint :: BS.ByteString -> (Word, BS.ByteString)
    decodeVarint bs = go' 0 0 bs
      where
        go' acc shift b
          | BS.null b = (acc, b)
          | otherwise =
              let byte = BS.index b 0
                  rest = BS.drop 1 b
                  val  = fromIntegral (byte .&. 0x7f)
                  acc' = acc .|. (val `shiftL` shift)
              in if byte .&. 0x80 == 0
                 then (acc', rest)
                 else go' acc' (shift + 7) rest

    encodeVarintBS :: Word -> BS.ByteString
    encodeVarintBS = BS.pack . encodeVarintList
      where
        encodeVarintList 0 = [0]
        encodeVarintList n = go'' n
        go'' 0 = []
        go'' n =
          let byte = fromIntegral (n .&. 0x7f)
              n'   = n `shiftR` 7
          in if n' == 0
             then [byte]
             else (byte .|. 0x80) : go'' n'

    (.&.) = (Data.Bits..&.)
    (.|.) = (Data.Bits..|.)
    shiftL = Data.Bits.shiftL
    shiftR = Data.Bits.shiftR

-- Encode a varint field (field number + varint value).
encodeVarintField :: Int -> Word -> BS.ByteString
encodeVarintField fieldNum val =
  let tag = fromIntegral (fieldNum * 8) :: Word  -- wire type 0
  in BS.append (encodeVarint tag) (encodeVarint val)

-- Encode a length-delimited field (field number + bytes).
encodeBytesField :: Int -> BS.ByteString -> BS.ByteString
encodeBytesField fieldNum dat =
  let tag = fromIntegral (fieldNum * 8 + 2) :: Word  -- wire type 2
  in BS.concat [encodeVarint tag, encodeVarint (fromIntegral (BS.length dat)), dat]

encodeVarint :: Word -> BS.ByteString
encodeVarint 0 = BS.singleton 0
encodeVarint n = BS.pack (go n)
  where
    go 0 = []
    go v =
      let byte = fromIntegral (v Data.Bits..&. 0x7f)
          v'   = v `Data.Bits.shiftR` 7
      in if v' == 0
         then [byte]
         else (byte Data.Bits..|. 0x80) : go v'
