apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: kafka-pubsub
spec:
  type: pubsub.kafka
  version: v1
  metadata:
    - name: brokers
      value: 127.0.0.1:9092
    - name: authRequired
      value: "false"
    - name: consumerGroup
      value: connector-service-group
    - name: publishTopic
      value: audit-trail-events
    - name: subscribeTopics
      value: audit-trail-events
