apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: redis-pubsub
spec:
  type: pubsub.redis
  version: v1
  metadata:
    - name: redisHost
      value: localhost:6379
    - name: redisPassword
      value: ""
    - name: enableTLS
      value: "false"
    - name: consumerID
      value: connector-service-group
    - name: processingTimeout
      value: 60
    - name: redeliverInterval
      value: 30
    - name: concurrency
      value: 10
    - name: queueDepth
      value: 100
    - name: activeDeadLetterListener
      value: true
