/**
 * ConnectorClient — high-level wrapper using UniFFI bindings via koffi.
 *
 * Handles the full round-trip for any payment flow:
 *   1. Serialize protobuf request to bytes
 *   2. Build connector HTTP request via UniffiClient.callReq (generic FFI dispatch)
 *   3. Execute the HTTP request via our standardized HttpClient
 *   4. Parse the connector response via UniffiClient.callRes (generic FFI dispatch)
 *   5. Deserialize protobuf response from bytes
 *
 * Flow methods (authorize, capture, void, refund, …) are generated into this file.
 * To add a new flow: edit sdk/flows.yaml and run `make generate`.
 */

import { Dispatcher } from "undici";
import { UniffiClient } from "./uniffi_client";
import { execute, createDispatcher, HttpOptions, HttpRequest } from "../http_client";
// @ts-ignore - protobuf generated files might not have types yet
import { ucs } from "./generated/proto";

const v2 = ucs.v2;

export class ConnectorClient {
  private uniffi: UniffiClient;
  private options: ucs.v2.IOptions;
  private dispatcher: Dispatcher;

  /**
   * @param libPath - optional path to the UniFFI shared library
   * @param options - unified SDK configuration from Protobuf (Options message)
   */
  constructor(libPath?: string, options: ucs.v2.IOptions = {}) {
    this.uniffi = new UniffiClient(libPath);
    this.options = options;

    // Instance-level cache: create the primary connection pool at startup
    this.dispatcher = createDispatcher(this.getNativeHttpOptions(options.http));
  }

  /**
   * Internal helper to map Protobuf HttpOptions to Native HttpClient options.
   */
  private getNativeHttpOptions(proto?: ucs.v2.IHttpOptions | null): HttpOptions {
    if (!proto) return {};

    return {
      totalTimeoutMs: proto.totalTimeoutMs ?? undefined,
      connectTimeoutMs: proto.connectTimeoutMs ?? undefined,
      responseTimeoutMs: proto.responseTimeoutMs ?? undefined,
      keepAliveTimeoutMs: proto.keepAliveTimeoutMs ?? undefined,
      proxy: proto.proxy ? {
        httpUrl: proto.proxy.httpUrl ?? undefined,
        httpsUrl: proto.proxy.httpsUrl ?? undefined,
        bypassUrls: proto.proxy.bypassUrls ?? undefined,
      } : undefined,
      caCert: proto.caCert ?? undefined,
    };
  }

  /**
   * Execute a full round-trip for any registered payment flow.
   *
   * Looks up the request/response protobuf type names from FLOWS, encodes the
   * request, calls callReq → HTTP → callRes via the generic FFI dispatcher,
   * then decodes and returns the response.
   *
   * @param flow - Flow name matching the FFI transformer prefix (e.g. "authorize").
   * @param requestMsg - Protobuf request message object.
   * @param metadata - Dict with connector routing and auth info.
   * @param ffiOptions - Optional IFfiOptions override.
   */
  async _executeFlow(
    flow: string,
    requestMsg: object,
    metadata: Record<string, string>,
    ffiOptions?: ucs.v2.IFfiOptions | null,
    reqTypeName?: string,
    resTypeName?: string
  ): Promise<unknown> {
    const reqType = reqTypeName ? (v2 as any)[reqTypeName] : undefined;
    const resType = resTypeName ? (v2 as any)[resTypeName] : undefined;

    if (!reqType || !resType) {
      throw new Error(`Unknown flow: '${flow}' or missing type names.`);
    }

    // 1. Serialize request
    const requestBytes = Buffer.from(reqType.encode(requestMsg).finish());

    // 2. Resolve FFI options (prefer call-specific)
    const ffi = ffiOptions || this.options.ffi;
    const optionsBytes = ffi ? Buffer.from(v2.FfiOptions.encode(ffi).finish()) : Buffer.alloc(0);

    // 3. Build connector HTTP request via FFI (returns FfiConnectorHttpRequest protobuf bytes)
    const resultBytes = this.uniffi.callReq(flow, requestBytes, metadata, optionsBytes);
    const connectorReq = v2.FfiConnectorHttpRequest.decode(resultBytes);

    const connectorRequest: HttpRequest = {
      url: connectorReq.url,
      method: connectorReq.method,
      headers: connectorReq.headers || {},
      body: connectorReq.body ?? undefined
    };

    // 4. Execute HTTP using the instance-owned connection pool
    const response = await execute(
      connectorRequest,
      this.getNativeHttpOptions(this.options.http),
      this.dispatcher
    );

    // 5. Encode HTTP response as FfiConnectorHttpResponse protobuf bytes
    const resProto = v2.FfiConnectorHttpResponse.create({
      statusCode: response.statusCode,
      headers: response.headers,
      body: response.body
    });
    const resBytes = Buffer.from(v2.FfiConnectorHttpResponse.encode(resProto).finish());

    // 6. Parse connector response via FFI and decode
    const resultBytesRes = this.uniffi.callRes(flow, resBytes, requestBytes, metadata, optionsBytes);
    return resType.decode(resultBytesRes);
  }

  // <GENERATED_FLOWS_START> - This section is auto-generated by sdk/codegen/generate.py
  // Do not edit manually. Run `make generate` to update.

  /** PaymentService.Authorize — Authorize a payment amount on a payment method. This reserves funds without capturing them, essential for verifying availability before finalizing. */
  async authorize(
    requestMsg: ucs.v2.IPaymentServiceAuthorizeRequest,
    metadata: Record<string, string>,
    ffiOptions?: ucs.v2.IFfiOptions | null
  ): Promise<ucs.v2.PaymentServiceAuthorizeResponse> {
    return this._executeFlow('authorize', requestMsg, metadata, ffiOptions, 'PaymentServiceAuthorizeRequest', 'PaymentServiceAuthorizeResponse') as Promise<ucs.v2.PaymentServiceAuthorizeResponse>;
  }

  /** PaymentService.Capture — Finalize an authorized payment transaction. Transfers reserved funds from customer to merchant account, completing the payment lifecycle. */
  async capture(
    requestMsg: ucs.v2.IPaymentServiceCaptureRequest,
    metadata: Record<string, string>,
    ffiOptions?: ucs.v2.IFfiOptions | null
  ): Promise<ucs.v2.PaymentServiceCaptureResponse> {
    return this._executeFlow('capture', requestMsg, metadata, ffiOptions, 'PaymentServiceCaptureRequest', 'PaymentServiceCaptureResponse') as Promise<ucs.v2.PaymentServiceCaptureResponse>;
  }

  /** MerchantAuthenticationService.CreateAccessToken — Generate short-lived connector authentication token. Provides secure credentials for connector API access without storing secrets client-side. */
  async create_access_token(
    requestMsg: ucs.v2.IMerchantAuthenticationServiceCreateAccessTokenRequest,
    metadata: Record<string, string>,
    ffiOptions?: ucs.v2.IFfiOptions | null
  ): Promise<ucs.v2.MerchantAuthenticationServiceCreateAccessTokenResponse> {
    return this._executeFlow('create_access_token', requestMsg, metadata, ffiOptions, 'MerchantAuthenticationServiceCreateAccessTokenRequest', 'MerchantAuthenticationServiceCreateAccessTokenResponse') as Promise<ucs.v2.MerchantAuthenticationServiceCreateAccessTokenResponse>;
  }

  /** PaymentService.Get — Retrieve current payment status from the payment processor. Enables synchronization between your system and payment processors for accurate state tracking. */
  async get(
    requestMsg: ucs.v2.IPaymentServiceGetRequest,
    metadata: Record<string, string>,
    ffiOptions?: ucs.v2.IFfiOptions | null
  ): Promise<ucs.v2.PaymentServiceGetResponse> {
    return this._executeFlow('get', requestMsg, metadata, ffiOptions, 'PaymentServiceGetRequest', 'PaymentServiceGetResponse') as Promise<ucs.v2.PaymentServiceGetResponse>;
  }

  /** PaymentService.Refund — Initiate a refund to customer's payment method. Returns funds for returns, cancellations, or service adjustments after original payment. */
  async refund(
    requestMsg: ucs.v2.IPaymentServiceRefundRequest,
    metadata: Record<string, string>,
    ffiOptions?: ucs.v2.IFfiOptions | null
  ): Promise<ucs.v2.RefundResponse> {
    return this._executeFlow('refund', requestMsg, metadata, ffiOptions, 'PaymentServiceRefundRequest', 'RefundResponse') as Promise<ucs.v2.RefundResponse>;
  }

  /** PaymentService.Void — Cancel an authorized payment before capture. Releases held funds back to customer, typically used when orders are cancelled or abandoned. */
  async void(
    requestMsg: ucs.v2.IPaymentServiceVoidRequest,
    metadata: Record<string, string>,
    ffiOptions?: ucs.v2.IFfiOptions | null
  ): Promise<ucs.v2.PaymentServiceVoidResponse> {
    return this._executeFlow('void', requestMsg, metadata, ffiOptions, 'PaymentServiceVoidRequest', 'PaymentServiceVoidResponse') as Promise<ucs.v2.PaymentServiceVoidResponse>;
  }

  // <GENERATED_FLOWS_END>
}
