[package]
name = "common_enums"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
strum = { version = "0.26", features = ["derive"] }
thiserror = "1.0"