use std::fs;
use std::path::Path;

fn main() {
    let manifest_dir = std::env::var("CARGO_MANIFEST_DIR").unwrap();
    let examples_dir = Path::new(&manifest_dir).join("../../../examples");
    let out_dir = std::env::var("OUT_DIR").unwrap();
    let connectors_path = format!("{out_dir}/connectors.rs");
    let scenarios_path = format!("{out_dir}/connector_scenarios.rs");

    // Rebuild if any example file changes
    println!("cargo:rerun-if-changed={}", examples_dir.display());

    // Known scenario function names (subset may be present in any connector)
    let all_scenarios: &[(&str, &str)] = &[
        ("checkout_autocapture", "process_checkout_autocapture"),
        ("checkout_card", "process_checkout_card"),
        ("checkout_wallet", "process_checkout_wallet"),
        ("checkout_bank", "process_checkout_bank"),
        ("refund", "process_refund"),
        ("recurring", "process_recurring"),
        ("void_payment", "process_void_payment"),
        ("get_payment", "process_get_payment"),
        ("create_customer", "process_create_customer"),
        ("tokenize", "process_tokenize"),
        ("authentication", "process_authentication"),
    ];

    let mut modules: Vec<(String, Vec<(&'static str, &'static str)>)> = Vec::new();

    if let Ok(entries) = fs::read_dir(&examples_dir) {
        let mut entries: Vec<_> = entries.flatten().collect();
        entries.sort_by_key(|e| e.file_name());

        for entry in entries {
            let name = entry.file_name().into_string().unwrap_or_default();
            let rs_file = entry.path().join("rust").join(format!("{name}.rs"));
            if !rs_file.exists() {
                continue;
            }

            println!("cargo:rerun-if-changed={}", rs_file.display());

            // Read the file to discover which process_* functions exist.
            // Only include connectors that use `pub async fn` (regenerated with new sdk_snippets.py).
            // Old files without `pub` are skipped to avoid compile errors from private function access.
            let content = fs::read_to_string(&rs_file).unwrap_or_default();
            let mut present = Vec::new();
            for (key, fn_name) in all_scenarios {
                // Only match public async functions (regenerated files)
                if content.contains(&format!("pub async fn {fn_name}(")) {
                    present.push((*key, *fn_name));
                }
            }

            if !present.is_empty() {
                modules.push((name, present));
            }
        }
    }

    // Generate connectors.rs: include each connector's Rust file as a module
    {
        let mut code = String::new();
        code.push_str("// AUTO-GENERATED by build.rs — do not edit manually.\n");
        code.push_str("// Lists all connector modules with generated process_* functions.\n\n");

        for (name, _) in &modules {
            let path = examples_dir
                .join(name)
                .join("rust")
                .join(format!("{name}.rs"));
            let canonical = path.canonicalize().unwrap_or(path.clone());
            code.push_str(&format!(
                "pub mod {name} {{\n    include!(r\"{}\");\n}}\n",
                canonical.display()
            ));
        }

        code.push_str("\npub const ALL_CONNECTORS: &[&str] = &[\n");
        for (name, _) in &modules {
            code.push_str(&format!("    \"{name}\",\n"));
        }
        code.push_str("];\n");

        fs::write(&connectors_path, code).unwrap();
    }

    // Generate connector_scenarios.rs: a match expression dispatching to each connector
    {
        let mut code = String::new();
        code.push_str("// AUTO-GENERATED by build.rs — do not edit manually.\n");
        code.push_str("// Match connector_name -> list of (scenario_key, Result) pairs.\n\n");
        code.push_str("match connector_name {\n");

        for (name, scenarios) in &modules {
            code.push_str(&format!("    \"{name}\" => {{\n"));
            code.push_str("        let mut results = vec![];\n");
            for (key, fn_name) in scenarios {
                code.push_str(&format!(
                    "        results.push((\"{key}\".to_string(), connectors::{name}::{fn_name}(client, &txn_id).await));\n"
                ));
            }
            code.push_str("        results\n");
            code.push_str("    }\n");
        }

        code.push_str("    _ => vec![],\n");
        code.push_str("}\n");

        fs::write(&scenarios_path, code).unwrap();
    }
}
