pub mod transformers;
use common_utils::Maskable;

use base64::Engine;
use common_enums;
use common_utils::{
    errors::CustomResult,
    ext_traits::{deserialize_xml_to_struct, BytesExt},
    request::RequestContent,
    types::MinorUnit,
};
use domain_types::{
    connector_flow::{
        Accept, Authenticate, Authorize, Capture, CreateConnectorCustomer, CreateOrder,
        CreateSessionToken, DefendDispute, PSync, PostAuthenticate, PreAuthenticate, RSync, Refund,
        RepeatPayment, SetupMandate, SubmitEvidence, Void, VoidPC,
    },
    connector_types::{
        AcceptDisputeData, ConnectorCustomerData, ConnectorCustomerResponse,
        ConnectorSpecifications, ConnectorWebhookSecrets, DisputeDefendData, DisputeFlowData,
        DisputeResponseData, EventType, PaymentCreateOrderData, PaymentCreateOrderResponse,
        PaymentFlowData, PaymentVoidData, PaymentsAuthenticateData, PaymentsAuthorizeData,
        PaymentsCancelPostCaptureData, PaymentsCaptureData, PaymentsPostAuthenticateData,
        PaymentsPreAuthenticateData, PaymentsResponseData, PaymentsSyncData, RefundFlowData,
        RefundSyncData, RefundWebhookDetailsResponse, RefundsData, RefundsResponseData,
        RepeatPaymentData, RequestDetails, SessionTokenRequestData, SessionTokenResponseData,
        SetupMandateRequestData, SubmitEvidenceData, WebhookDetailsResponse,
    },
    errors::{self, ConnectorError},
    payment_method_data::PaymentMethodDataTypes,
    router_data::{ConnectorAuthType, ErrorResponse},
    router_data_v2::RouterDataV2,
    router_response_types::Response,
    types::Connectors,
};
use error_stack::ResultExt;
// use crate::masking::{Maskable, PeekInterface};
use interfaces::{
    api::ConnectorCommon,
    connector_integration_v2::ConnectorIntegrationV2,
    connector_types::{
        AcceptDispute, ConnectorServiceTrait,
        CreateConnectorCustomer as CreateConnectorCustomerTrait, DisputeDefend, IncomingWebhook,
        PaymentAuthenticateV2, PaymentAuthorizeV2, PaymentCapture, PaymentOrderCreate,
        PaymentPostAuthenticateV2, PaymentPreAuthenticateV2, PaymentSessionToken, PaymentSyncV2,
        PaymentVoidPostCaptureV2, PaymentVoidV2, RefundSyncV2, RefundV2, RepeatPaymentV2,
        SetupMandateV2, SubmitEvidenceV2, ValidationTrait,
    },
    events::connector_api_logs::ConnectorEvent,
    verification::SourceVerification,
};
use serde::Serialize;
use self::transformers::{
    CnpOnlineResponse, VantivSyncResponse, WorldpayvantivAuthType, WorldpayvantivPaymentsRequest,
    BASE64_ENGINE,
};
use super::macros;
use crate::{types::ResponseRouterData, with_response_body};
pub(crate) mod headers {
    pub(crate) const AUTHORIZATION: &str = "Authorization";
}
// Trait implementations will be generated by macros

impl<T: PaymentMethodDataTypes + Debug + Sync + Send + 'static + Serialize> IncomingWebhook
    for Worldpayvantiv<T>
{
    fn verify_webhook_source(
        &self,
        _request: RequestDetails,
        _connector_webhook_secret: Option<ConnectorWebhookSecrets>,
        _connector_account_details: Option<ConnectorAuthType>,
    ) -> Result<bool, error_stack::Report<ConnectorError>> {
        Ok(false) // WorldpayVantiv doesn't support webhooks
    }
    
    fn get_event_type(
        &self,
        _request: RequestDetails,
    ) -> Result<EventType, error_stack::Report<ConnectorError>> {
        Err(error_stack::report!(ConnectorError::WebhooksNotImplemented))
    }
    
    fn process_payment_webhook(
        &self,
        _request: RequestDetails,
    ) -> Result<WebhookDetailsResponse, error_stack::Report<ConnectorError>> {
        Err(error_stack::report!(ConnectorError::WebhooksNotImplemented))
    }
    
    fn process_refund_webhook(
        &self,
        _request: RequestDetails,
    ) -> Result<RefundWebhookDetailsResponse, error_stack::Report<ConnectorError>> {
        Err(error_stack::report!(ConnectorError::WebhooksNotImplemented))
    }
}
    > DisputeDefend for Worldpayvantiv<T>
    > RefundSyncV2 for Worldpayvantiv<T>
    > AcceptDispute for Worldpayvantiv<T>
    // Basic connector implementation
impl<T: PaymentMethodDataTypes + Debug + Sync + Send + 'static + Serialize> ConnectorCommon
    for Worldpayvantiv<T>
{
    fn id(&self) -> &'static str {
        "worldpayvantiv"
    }
    
    fn common_get_content_type(&self) -> &'static str {
        "text/xml"
    }
    
    fn base_url<'a>(&self, connectors: &'a Connectors) -> &'a str {
        connectors.worldpayvantiv.base_url.as_ref()
    }
    
    fn build_error_response(
        res: Response,
        event_builder: Option<&mut ConnectorEvent>,
    ) -> CustomResult<ErrorResponse, errors::ConnectorError> {
        let response_str = std::str::from_utf8(&res.response)
            .map_err(|_| ConnectorError::ResponseDeserializationFailed)?;
        let response: transformers::CnpOnlineResponse = deserialize_xml_to_struct(response_str)
            .map_err(|_parse_error| ConnectorError::ResponseDeserializationFailed)?;
        with_response_body!(event_builder, response);
        Ok(ErrorResponse {
            status_code: res.status_code,
            code: response.response_code,
            message: response.message.clone(),
            reason: Some(response.message),
            attempt_status: None,
            connector_transaction_id: None,
            network_decline_code: None,
            network_advice_code: None,
            network_error_message: None,
        })
    }
    
    fn get_currency_unit(&self) -> common_enums::CurrencyUnit {
        common_enums::CurrencyUnit::Minor
    }
}
// Define connector prerequisites for payment flows (XML-based)
// Group flows by unique request/response combinations to avoid duplicate templating structs
macros::create_all_prerequisites!(
    connector_name: Worldpayvantiv,
    generic_type: T,
    api: [
        (
            flow: Authorize,
            request_body: WorldpayvantivPaymentsRequest<T>,
            response_body: CnpOnlineResponse,
            router_data: RouterDataV2<Authorize, PaymentFlowData, PaymentsAuthorizeData<T>, PaymentsResponseData>,
        ),
        (
            flow: PSync,
            response_body: VantivSyncResponse,
            router_data: RouterDataV2<PSync, PaymentFlowData, PaymentsSyncData, PaymentsResponseData>,
        ),
    ],
    amount_converters: [
        amount_converter: MinorUnit
    ],
    member_functions: {
        fn preprocess_response_bytes<F, FCD, Req, Res>(
            &self,
            _req: &RouterDataV2<F, FCD, Req, Res>,
            bytes: bytes::Bytes,
        ) -> CustomResult<bytes::Bytes, errors::ConnectorError> {
            // Convert XML responses to JSON format for the macro's JSON parser
            let response_str = std::str::from_utf8(&bytes)
                .change_context(errors::ConnectorError::ResponseDeserializationFailed)?;
            // Parse XML to struct, then serialize back to JSON
            if response_str.trim().starts_with("<?xml") || response_str.trim().starts_with("<") {
                // This is an XML response - convert to JSON
                let xml_response: CnpOnlineResponse = deserialize_xml_to_struct(response_str)
                    .change_context(errors::ConnectorError::ResponseDeserializationFailed)?;
                let json_bytes = serde_json::to_vec(&xml_response)
                    .change_context(errors::ConnectorError::ResponseDeserializationFailed)?;
                Ok(bytes::Bytes::from(json_bytes))
            } else {
                // This is already JSON or another format
                Ok(bytes)
            }
        }
        
        pub fn build_headers<F, FCD, Req, Res>(
            &self,
            req: &RouterDataV2<F, FCD, Req, Res>,
        ) -> CustomResult<Vec<(String, Maskable<String>)>, ConnectorError> {
            let mut header = vec![];
            let mut api_key = self.get_auth_header(&req.connector_auth_type)?;
            header.append(&mut api_key);
            Ok(header)
        }
        
        pub fn connector_base_url_payments<F, Req, Res>(
            &self,
            req: &RouterDataV2<F, PaymentFlowData, Req, Res>,
        ) -> String {
            let base_url = &req.resource_common_data.connectors.worldpayvantiv.base_url;
            base_url.to_string()
        }
        
        pub fn connector_base_url_refunds<F, Req, Res>(
            &self,
            req: &RouterDataV2<F, RefundFlowData, Req, Res>,
        ) -> String {
            req.resource_common_data.connectors.worldpayvantiv.base_url.to_string()
        }
        
        pub fn get_auth_header(
            &self,
            auth_type: &ConnectorAuthType,
        ) -> CustomResult<Vec<(String, Maskable<String>)>, ConnectorError> {
            let auth = WorldpayvantivAuthType::try_from(auth_type)?;
            let auth_key = format!("{}:{}", auth.user.peek(), auth.password.peek());
            let auth_header = format!("Basic {}", BASE64_ENGINE.encode(auth_key));
            Ok(vec![(
                headers::AUTHORIZATION.to_string(),
                auth_header.into(),
            )])
        }
);
// Implement the specific flows
macros::macro_connector_implementation!(
    connector_default_implementations: [get_content_type, get_error_response_v2],
    connector: Worldpayvantiv,
    curl_request: Xml(WorldpayvantivPaymentsRequest<T>),
    curl_response: CnpOnlineResponse,
    flow_name: Authorize,
    resource_common_data: PaymentFlowData,
    flow_request: PaymentsAuthorizeData<T>,
    flow_response: PaymentsResponseData,
    http_method: Post,
    preprocess_response: true,
    [PaymentMethodDataTypes + std::fmt::Debug + std::marker::Sync + std::marker::Send + 'static + Serialize],
    other_functions: {
        fn get_headers(
            req: &RouterDataV2<Authorize, PaymentFlowData, PaymentsAuthorizeData<T>, PaymentsResponseData>,
            self.build_headers(req)
        fn get_url(
        ) -> CustomResult<String, ConnectorError> {
            Ok(self.connector_base_url_payments(req).to_string())
    curl_response: VantivSyncResponse,
    flow_name: PSync,
    flow_request: PaymentsSyncData,
    http_method: Get,
            req: &RouterDataV2<PSync, PaymentFlowData, PaymentsSyncData, PaymentsResponseData>,
            self.get_auth_header(&req.connector_auth_type)
            let txn_id = req.request.get_connector_transaction_id()
                .change_context(ConnectorError::MissingConnectorTransactionID)?;
            let secondary_base_url = req.resource_common_data.connectors.worldpayvantiv.secondary_base_url
                .as_ref()
                .unwrap_or(&req.resource_common_data.connectors.worldpayvantiv.base_url);
            Ok(format!(
                "{secondary_base_url}/reports/dtrPaymentStatus/{txn_id}"
            ))
// Manual implementations for flows that share request/response types
    > ConnectorIntegrationV2<Capture, PaymentFlowData, PaymentsCaptureData, PaymentsResponseData>
    for Worldpayvantiv<T>
    fn get_headers(
        req: &RouterDataV2<Capture, PaymentFlowData, PaymentsCaptureData, PaymentsResponseData>,
    ) -> CustomResult<Vec<(String, Maskable<String>)>, ConnectorError> {
        self.build_headers(req)
    fn get_content_type(&self) -> &'static str {
        self.common_get_content_type()
    fn get_url(
    ) -> CustomResult<String, ConnectorError> {
        Ok(self.connector_base_url_payments(req).to_string())
    fn get_request_body(
    ) -> CustomResult<Option<RequestContent>, ConnectorError> {
        let request = WorldpayvantivPaymentsRequest::try_from(WorldpayvantivRouterData {
            router_data: req.clone(),
            connector: self.clone(),
        })?;
        Ok(Some(RequestContent::Xml(Box::new(request))))
    fn handle_response_v2(
        data: &RouterDataV2<Capture, PaymentFlowData, PaymentsCaptureData, PaymentsResponseData>,
    ) -> CustomResult<
        RouterDataV2<Capture, PaymentFlowData, PaymentsCaptureData, PaymentsResponseData>,
        ConnectorError,
    > {
            .change_context(ConnectorError::ResponseDeserializationFailed)?;
        let response: CnpOnlineResponse = deserialize_xml_to_struct(response_str)
        if let Some(i) = event_builder {
            i.set_response_body(&response)
        RouterDataV2::try_from(ResponseRouterData {
            response,
            router_data: data.clone(),
            http_code: res.status_code,
    fn get_error_response_v2(
    ) -> CustomResult<ErrorResponse, ConnectorError> {
        self.build_error_response(res, event_builder)
    fn get_http_method(&self) -> common_utils::request::Method {
        common_utils::request::Method::Post
    > ConnectorIntegrationV2<Void, PaymentFlowData, PaymentVoidData, PaymentsResponseData>
        req: &RouterDataV2<Void, PaymentFlowData, PaymentVoidData, PaymentsResponseData>,
        data: &RouterDataV2<Void, PaymentFlowData, PaymentVoidData, PaymentsResponseData>,
        RouterDataV2<Void, PaymentFlowData, PaymentVoidData, PaymentsResponseData>,
        VoidPC,
        PaymentsCancelPostCaptureData,
        req: &RouterDataV2<
            VoidPC,
            PaymentFlowData,
            PaymentsCancelPostCaptureData,
            PaymentsResponseData,
        >,
        data: &RouterDataV2<
        RouterDataV2<VoidPC, PaymentFlowData, PaymentsCancelPostCaptureData, PaymentsResponseData>,
    > ConnectorIntegrationV2<Refund, RefundFlowData, RefundsData, RefundsResponseData>
        req: &RouterDataV2<Refund, RefundFlowData, RefundsData, RefundsResponseData>,
        Ok(self.connector_base_url_refunds(req).to_string())
        data: &RouterDataV2<Refund, RefundFlowData, RefundsData, RefundsResponseData>,
        RouterDataV2<Refund, RefundFlowData, RefundsData, RefundsResponseData>,
    > ConnectorIntegrationV2<RSync, RefundFlowData, RefundSyncData, RefundsResponseData>
        req: &RouterDataV2<RSync, RefundFlowData, RefundSyncData, RefundsResponseData>,
        self.get_auth_header(&req.connector_auth_type)
        "application/json"
        let refund_id = req.request.connector_refund_id.clone();
        let secondary_base_url = req
            .resource_common_data
            .connectors
            .worldpayvantiv
            .secondary_base_url
            .as_ref()
            .unwrap_or(&req.resource_common_data.connectors.worldpayvantiv.base_url);
        Ok(format!(
            "{}/reports/dtrPaymentStatus/{}",
            secondary_base_url, refund_id
        ))
        _req: &RouterDataV2<RSync, RefundFlowData, RefundSyncData, RefundsResponseData>,
        // GET request doesn't need a body
        Ok(None)
        data: &RouterDataV2<RSync, RefundFlowData, RefundSyncData, RefundsResponseData>,
        RouterDataV2<RSync, RefundFlowData, RefundSyncData, RefundsResponseData>,
        let response: VantivSyncResponse = res
            .response
            .parse_struct("VantivSyncResponse")
        common_utils::request::Method::Get
        SetupMandate,
        SetupMandateRequestData<T>,
    ConnectorIntegrationV2<RepeatPayment, PaymentFlowData, RepeatPaymentData, PaymentsResponseData>
// Empty implementations for dispute flows
    > ConnectorIntegrationV2<Accept, DisputeFlowData, AcceptDisputeData, DisputeResponseData>
    ConnectorIntegrationV2<SubmitEvidence, DisputeFlowData, SubmitEvidenceData, DisputeResponseData>
    > ConnectorIntegrationV2<DefendDispute, DisputeFlowData, DisputeDefendData, DisputeResponseData>
// Empty implementations for order flows
        CreateOrder,
        PaymentCreateOrderData,
        PaymentCreateOrderResponse,
        CreateSessionToken,
        SessionTokenRequestData,
        SessionTokenResponseData,
impl<T: PaymentMethodDataTypes + std::fmt::Debug + Sync + Send + 'static + Serialize>
        domain_types::connector_flow::CreateAccessToken,
        domain_types::connector_types::AccessTokenRequestData,
        domain_types::connector_types::AccessTokenResponseData,
        domain_types::connector_flow::PaymentMethodToken,
        domain_types::connector_types::PaymentMethodTokenizationData<T>,
        domain_types::connector_types::PaymentMethodTokenResponse,
// SourceVerification implementations for all flows
    > SourceVerification<Authorize, PaymentFlowData, PaymentsAuthorizeData<T>, PaymentsResponseData>
    SourceVerification<
    > SourceVerification<PSync, PaymentFlowData, PaymentsSyncData, PaymentsResponseData>
    > SourceVerification<Capture, PaymentFlowData, PaymentsCaptureData, PaymentsResponseData>
    > SourceVerification<Void, PaymentFlowData, PaymentVoidData, PaymentsResponseData>
    SourceVerification<VoidPC, PaymentFlowData, PaymentsCancelPostCaptureData, PaymentsResponseData>
    > SourceVerification<Refund, RefundFlowData, RefundsData, RefundsResponseData>
    > SourceVerification<RSync, RefundFlowData, RefundSyncData, RefundsResponseData>
    > SourceVerification<RepeatPayment, PaymentFlowData, RepeatPaymentData, PaymentsResponseData>
    > SourceVerification<Accept, DisputeFlowData, AcceptDisputeData, DisputeResponseData>
    > SourceVerification<SubmitEvidence, DisputeFlowData, SubmitEvidenceData, DisputeResponseData>
    > SourceVerification<DefendDispute, DisputeFlowData, DisputeDefendData, DisputeResponseData>
        CreateConnectorCustomer,
        ConnectorCustomerData,
        ConnectorCustomerResponse,
    > ConnectorSpecifications for Worldpayvantiv<T>
