[package]
name = "proto-codegen"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "proto-codegen"
path = "src/main.rs"

[dependencies]
clap = { version = "4.5", features = ["derive"] }
anyhow = "1.0"
tonic-build = "0.11"
prost-build = "0.12"
tempfile = "3.0"