/*
 * gRPC smoke test for the hyperswitch-payments Rust gRPC SDK.
 *
 * For each supported flow (filtered by data/field_probe/{connector}.json),
 * calls the connector's build_*_request() builder to construct the proto
 * request, then dispatches it directly through the GrpcClient.
 *
 * No grpc_* wrapper functions are needed in the connector Rust file.
 *
 * Usage:
 *   cargo run --bin grpc-smoke-test -- --creds-file creds.json --connector stripe
 *   cargo run --bin grpc-smoke-test -- --endpoint http://localhost:8000 \
 *       --connector stripe --auth-type header-key --api-key sk_test_...
 */

// Connector modules auto-generated by build.rs from examples/{connector}/rust/*.rs.
mod connectors {
    include!(concat!(env!("OUT_DIR"), "/connectors.rs"));
}

// Self-auth helper async fns (capture, void) — must be at module level.
include!(concat!(env!("OUT_DIR"), "/grpc_helpers.rs"));

use grpc_api_types::health_check::{health_client::HealthClient, HealthCheckRequest};
use hyperswitch_payments_client::{GrpcClient, GrpcConfig, Secret};
use std::error::Error;
use std::time::Duration;
use tokio::time::sleep;
use tonic::{transport::Channel, Code as TonicCode};

// ── ANSI helpers ──────────────────────────────────────────────────────────────
fn no_color() -> bool {
    std::env::var("NO_COLOR").is_ok()
        || (std::env::var("FORCE_COLOR").is_err()
            && std::env::var("TERM").map_or(true, |t| t.is_empty() || t == "dumb"))
}
fn c(code: &str, text: &str) -> String {
    if no_color() {
        text.to_string()
    } else {
        format!("\x1b[{code}m{text}\x1b[0m")
    }
}
fn green(t: &str) -> String {
    c("32", t)
}
fn yellow(t: &str) -> String {
    c("33", t)
}
fn red(t: &str) -> String {
    c("31", t)
}
fn grey(t: &str) -> String {
    c("90", t)
}
fn bold(t: &str) -> String {
    c("1", t)
}

// ── Credentials loading ───────────────────────────────────────────────────────

/// Extract a string value from a creds.json field, which may be either
/// a plain string or a `{"value": "..."}` wrapper object.
fn extract_creds_value(obj: &serde_json::Value, keys: &[&str]) -> Option<String> {
    for key in keys {
        match obj.get(*key) {
            Some(serde_json::Value::String(s)) if !s.is_empty() => return Some(s.clone()),
            Some(serde_json::Value::Object(m)) => {
                if let Some(serde_json::Value::String(inner)) = m.get("value") {
                    if !inner.is_empty() {
                        return Some(inner.clone());
                    }
                }
            }
            _ => {}
        }
    }
    None
}

// Kept for backward-compat: the old flat grpc-creds.json format where
// endpoint, connector, auth_type, api_key are top-level fields.
#[derive(serde::Deserialize)]
struct FlatCreds {
    endpoint: String,
    connector: String,
    auth_type: String,
    api_key: String,
    #[serde(default)]
    api_secret: Option<String>,
    #[serde(default)]
    key1: Option<String>,
    #[serde(default)]
    merchant_id: Option<String>,
    #[serde(default)]
    tenant_id: Option<String>,
}

impl From<FlatCreds> for GrpcConfig {
    fn from(c: FlatCreds) -> Self {
        GrpcConfig {
            endpoint: c.endpoint,
            connector: c.connector,
            auth_type: c.auth_type,
            api_key: Secret::new(c.api_key),
            api_secret: c.api_secret.map(Secret::new),
            key1: c.key1.map(Secret::new),
            merchant_id: c.merchant_id,
            tenant_id: c.tenant_id,
        }
    }
}

// ── Health-check polling ──────────────────────────────────────────────────────

async fn wait_for_server(endpoint: &str, max_secs: u32) -> Result<(), String> {
    for attempt in 1..=max_secs {
        let channel = Channel::from_shared(endpoint.to_string())
            .map_err(|e| format!("Invalid endpoint URI: {e}"))?
            .connect_lazy();

        let mut health = HealthClient::new(channel);
        match health
            .check(HealthCheckRequest {
                service: String::new(),
            })
            .await
        {
            Ok(_) => return Ok(()),
            Err(s) if s.code() == TonicCode::Unavailable => {
                eprintln!(
                    "  {}",
                    grey(&format!(
                        "attempt {attempt}/{max_secs}: server not ready yet, retrying…"
                    ))
                );
                sleep(Duration::from_secs(1)).await;
            }
            Err(_) => return Ok(()), // any other status → server is up
        }
    }
    Err(format!(
        "server not ready after {max_secs}s — is grpc-server running at {endpoint}?"
    ))
}

// ── gRPC scenario dispatch ────────────────────────────────────────────────────

/// Calls all gRPC flows for `connector_name` discovered by build.rs.
/// build.rs generates grpc_scenarios.rs as a match expression that calls
/// connector builder functions directly — no grpc_* wrappers needed.
async fn run_grpc_scenarios(
    connector_name: &str,
    client: &GrpcClient,
) -> Vec<(String, Result<String, Box<dyn Error>>)> {
    include!(concat!(env!("OUT_DIR"), "/grpc_scenarios.rs"))
}

// ── Argument parsing ──────────────────────────────────────────────────────────

struct Args {
    creds_file: Option<String>,
    endpoint: Option<String>,
    connector: Option<String>,
    auth_type: Option<String>,
    api_key: Option<String>,
    api_secret: Option<String>,
    key1: Option<String>,
    merchant_id: Option<String>,
    tenant_id: Option<String>,
}

fn parse_args() -> Args {
    let raw: Vec<String> = std::env::args().skip(1).collect();
    let mut args = Args {
        creds_file: None,
        endpoint: None,
        connector: None,
        auth_type: None,
        api_key: None,
        api_secret: None,
        key1: None,
        merchant_id: None,
        tenant_id: None,
    };
    let mut i = 0usize;
    while i < raw.len() {
        macro_rules! next {
            () => {{
                i += 1;
                raw.get(i).cloned().unwrap_or_default()
            }};
        }
        match raw[i].as_str() {
            "--creds-file" => args.creds_file = Some(next!()),
            "--endpoint" => args.endpoint = Some(next!()),
            "--connector" => args.connector = Some(next!()),
            "--auth-type" => args.auth_type = Some(next!()),
            "--api-key" => args.api_key = Some(next!()),
            "--api-secret" => args.api_secret = Some(next!()),
            "--key1" => args.key1 = Some(next!()),
            "--merchant-id" => args.merchant_id = Some(next!()),
            "--tenant-id" => args.tenant_id = Some(next!()),
            "--help" | "-h" => {
                println!("Usage: grpc-smoke-test [options]");
                println!("  --creds-file <path>   JSON creds file (default: creds.json)");
                println!("  --endpoint <url>      gRPC server endpoint");
                println!("  --connector <name>    Connector name (e.g. stripe)");
                println!("  --auth-type <type>    Auth type (e.g. header-key)");
                println!("  --api-key <key>       API key");
                std::process::exit(0);
            }
            _ => {}
        }
        i += 1;
    }
    args
}

fn build_config(args: Args) -> Result<GrpcConfig, String> {
    let creds_file = args.creds_file.as_deref().unwrap_or("creds.json");
    let mut config: GrpcConfig = if std::path::Path::new(creds_file).exists() {
        let text = std::fs::read_to_string(creds_file)
            .map_err(|e| format!("Cannot read {creds_file}: {e}"))?;
        let raw: serde_json::Value = serde_json::from_str(&text)
            .map_err(|e| format!("Invalid JSON in {creds_file}: {e}"))?;
        // Flat format: top-level "endpoint" and "connector" keys (legacy grpc-creds.json style).
        if raw.get("endpoint").and_then(|v| v.as_str()).is_some() {
            let creds: FlatCreds = serde_json::from_value(raw)
                .map_err(|e| format!("Invalid format in {creds_file}: {e}"))?;
            creds.into()
        } else {
            // creds.json format: { "<connector>": { "api_key": {"value": "..."}, ... } }
            let connector = args.connector.as_deref().unwrap_or("stripe");
            let entry = raw
                .get(connector)
                .ok_or_else(|| format!("Connector '{connector}' not found in {creds_file}"))?;
            GrpcConfig {
                endpoint: args
                    .endpoint
                    .clone()
                    .unwrap_or_else(|| "http://localhost:8000".to_string()),
                connector: connector.to_string(),
                auth_type: args
                    .auth_type
                    .clone()
                    .unwrap_or_else(|| "header-key".to_string()),
                api_key: Secret::new(extract_creds_value(entry, &["api_key"]).unwrap_or_default()),
                api_secret: extract_creds_value(entry, &["api_secret"]).map(Secret::new),
                key1: extract_creds_value(entry, &["key1"]).map(Secret::new),
                merchant_id: extract_creds_value(entry, &["merchant_account", "merchant_id"]),
                tenant_id: extract_creds_value(entry, &["tenant_id"]),
            }
        }
    } else {
        GrpcConfig {
            endpoint: args
                .endpoint
                .clone()
                .ok_or("--endpoint required when no creds file")?,
            connector: args
                .connector
                .clone()
                .ok_or("--connector required when no creds file")?,
            auth_type: args
                .auth_type
                .clone()
                .unwrap_or_else(|| "header-key".to_string()),
            api_key: Secret::new(
                args.api_key
                    .clone()
                    .ok_or("--api-key required when no creds file")?,
            ),
            api_secret: args.api_secret.clone().map(Secret::new),
            key1: args.key1.clone().map(Secret::new),
            merchant_id: args.merchant_id.clone(),
            tenant_id: args.tenant_id.clone(),
        }
    };
    if let Some(v) = args.endpoint {
        config.endpoint = v;
    }
    if let Some(v) = args.connector {
        config.connector = v;
    }
    if let Some(v) = args.auth_type {
        config.auth_type = v;
    }
    if let Some(v) = args.api_key {
        config.api_key = Secret::new(v);
    }
    if args.api_secret.is_some() {
        config.api_secret = args.api_secret.map(Secret::new);
    }
    if args.key1.is_some() {
        config.key1 = args.key1.map(Secret::new);
    }
    if args.merchant_id.is_some() {
        config.merchant_id = args.merchant_id;
    }
    if args.tenant_id.is_some() {
        config.tenant_id = args.tenant_id;
    }
    Ok(config)
}

fn print_non_sensitive_config() {
    println!("\n{}", "=".repeat(60));
    println!("{}", bold("gRPC Smoke Test"));
    println!("{}", "=".repeat(60));
    println!();
}

// ── Main ──────────────────────────────────────────────────────────────────────

#[tokio::main]
async fn main() {
    let args = parse_args();
    let config = build_config(args).unwrap_or_else(|e| {
        eprintln!("{}", red(&format!("Configuration error: {e}")));
        std::process::exit(1);
    });

    // Print only non-sensitive configuration fields.
    print_non_sensitive_config();

    // ── Wait for server ───────────────────────────────────────────────────────
    println!("Waiting for gRPC server (up to 30s)…");
    if let Err(e) = wait_for_server(&config.endpoint, 30).await {
        eprintln!("{}", red(&format!("Server not available: {e}")));
        std::process::exit(1);
    }
    println!("{}\n", green("  Server ready."));

    // ── Connect ───────────────────────────────────────────────────────────────
    let connector_name = config.connector.clone();
    let endpoint = config.endpoint.clone();
    let client = GrpcClient::new(config).await.unwrap_or_else(|e| {
        eprintln!("{}", red(&format!("Failed to connect to {endpoint}: {e}")));
        std::process::exit(1);
    });

    // ── Scenarios ─────────────────────────────────────────────────────────────
    println!("Running gRPC scenarios for {}…", bold(&connector_name));
    let scenario_results = run_grpc_scenarios(&connector_name, &client).await;

    if scenario_results.is_empty() {
        println!(
            "{}",
            yellow(&format!(
                "  SKIPPED — no supported gRPC flows found for {connector_name}"
            ))
        );
        println!("  Add `pub fn build_*_request(...)` builder functions in examples/{connector_name}/rust/{connector_name}.rs");
        println!(
            "  and ensure flows are marked as supported in data/field_probe/{connector_name}.json."
        );
        std::process::exit(0);
    }

    let mut failed = false;
    for (key, result) in &scenario_results {
        print!("  [{key}] running … ");
        use std::io::Write;
        std::io::stdout().flush().ok();
        match result {
            Ok(msg) => println!("{} {}", green("✓ ok"), grey(&format!("— {msg}"))),
            Err(e) => {
                // Parse the tonic status code from the error string to decide pass vs fail.
                // tonic::Status Display is "status: <Code>, message: <msg>"
                let detail = e.to_string();
                let is_transport = detail.contains("Unavailable")
                    || detail.contains("DeadlineExceeded")
                    || detail.contains("connection refused")
                    || detail.contains("transport error");
                if is_transport {
                    println!("{} {}", red("✗ FAILED"), grey(&format!("— {detail}")));
                    failed = true;
                } else {
                    println!(
                        "{} {}",
                        yellow("~ connector error"),
                        grey(&format!("— {detail}"))
                    );
                }
            }
        }
    }

    // ── Result ────────────────────────────────────────────────────────────────
    println!();
    if failed {
        println!(
            "{}",
            red("gRPC smoke test FAILED (transport error — server unreachable or crashed)")
        );
        std::process::exit(1);
    }
    println!(
        "{} ({} scenario(s))",
        green("gRPC smoke test PASSED"),
        scenario_results.len()
    );
}
