name: Docker Build and Push to GHCR

on:
  workflow_dispatch:
    inputs:
      ref:
        description: 'Branch, tag or commit ID'
        required: false
        type: string

jobs:
  build-and-push-dockerfile:
    permissions:
      contents: read
      packages: write
    strategy:
      matrix:
        include:
          - platform: linux/amd64
            tag: linux-amd64
            os: ubuntu-latest
          - platform: linux/arm64
            tag: linux-arm64
            os: ubuntu-24.04-arm
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.ref || github.ref}}


      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set nightly version
        run: |
          COMMIT_SHA=$(git rev-parse HEAD)
          SHORT_SHA=${COMMIT_SHA::7}
          REF_INPUT="${{ github.event.inputs.ref }}"
          
          # Use ref input if provided, otherwise use commit hash
          if [ -n "$REF_INPUT" ]; then
            # Clean the ref input to make it suitable for Docker tag (replace / with -)
            REF_CLEAN=$(echo "$REF_INPUT" | sed 's/\//-/g')
            VERSION="0.1.0-nightly.$(date +'%Y%m%d')-${REF_CLEAN}"
          else
            VERSION="0.1.0-nightly.$(date +'%Y%m%d')-${SHORT_SHA}"
          fi
          
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Extract metadata for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository }}
          tags: |
            type=ref,event=branch,separator=_
            type=raw,value=${{ env.VERSION }}

      - name: Build Docker image (Dockerfile)
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile
          platforms: ${{ matrix.platform }}
          tags: ghcr.io/${{ github.repository }}:${{ env.VERSION }}-${{ matrix.tag }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          push: true
        env:
          CARGO_INCREMENTAL: "0"
          RUSTFLAGS: "-A warnings"
          SCCACHE_ENABLE: "true"

  create-manifest:
    needs: [build-and-push-dockerfile]
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.ref }}
      
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Set nightly version
        run: |
          COMMIT_SHA=$(git rev-parse HEAD)
          SHORT_SHA=${COMMIT_SHA::7}
          REF_INPUT="${{ github.event.inputs.ref }}"
          
          # Use ref input if provided, otherwise use commit hash
          if [ -n "$REF_INPUT" ]; then
            # Clean the ref input to make it suitable for Docker tag (replace / with -)
            REF_CLEAN=$(echo "$REF_INPUT" | sed 's/\//-/g')
            VERSION="0.1.0-nightly.$(date +'%Y%m%d')-${REF_CLEAN}"
          else
            VERSION="0.1.0-nightly.$(date +'%Y%m%d')-${SHORT_SHA}"
          fi
          
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Create manifest
        run: |
          docker buildx imagetools create --tag ghcr.io/${{ github.repository }}:${{ env.VERSION }} \
            ghcr.io/${{ github.repository }}:${{ env.VERSION }}-linux-amd64 \
            ghcr.io/${{ github.repository }}:${{ env.VERSION }}-linux-arm64
