// This file was autogenerated by some hot garbage in the `uniffi` crate.
// Trust me, you don't want to mess with it!

@file:Suppress("NAME_SHADOWING")

package io.juspay.connector

// Common helper code.
//
// Ideally this would live in a separate .kt file where it can be unittested etc
// in isolation, and perhaps even published as a re-useable package.
//
// However, it's important that the details of how this helper code works (e.g. the
// way that different builtin types are passed across the FFI) exactly match what's
// expected by the Rust code on the other side of the interface. In practice right
// now that means coming from the exact some version of `uniffi` that was used to
// compile the Rust component. The easiest way to ensure this is to bundle the Kotlin
// helpers directly inline like we're doing here.

import com.sun.jna.Library
import com.sun.jna.IntegerType
import com.sun.jna.Native
import com.sun.jna.Pointer
import com.sun.jna.Structure
import com.sun.jna.Callback
import com.sun.jna.ptr.*
import java.nio.ByteBuffer
import java.nio.ByteOrder
import java.nio.CharBuffer
import java.nio.charset.CodingErrorAction
import java.util.concurrent.atomic.AtomicLong
import java.util.concurrent.ConcurrentHashMap
import java.util.concurrent.atomic.AtomicBoolean

// This is a helper for safely working with byte buffers returned from the Rust code.
// A rust-owned buffer is represented by its capacity, its current length, and a
// pointer to the underlying data.

/**
 * @suppress
 */
@Structure.FieldOrder("capacity", "len", "data")
open class RustBuffer : Structure() {
    // Note: `capacity` and `len` are actually `ULong` values, but JVM only supports signed values.
    // When dealing with these fields, make sure to call `toULong()`.
    @JvmField var capacity: Long = 0
    @JvmField var len: Long = 0
    @JvmField var data: Pointer? = null

    class ByValue: RustBuffer(), Structure.ByValue
    class ByReference: RustBuffer(), Structure.ByReference

   internal fun setValue(other: RustBuffer) {
        capacity = other.capacity
        len = other.len
        data = other.data
    }

    companion object {
        internal fun alloc(size: ULong = 0UL) = uniffiRustCall() { status ->
            // Note: need to convert the size to a `Long` value to make this work with JVM.
            UniffiLib.INSTANCE.ffi_connector_ffi_uniffi_rustbuffer_alloc(size.toLong(), status)
        }.also {
            if(it.data == null) {
               throw RuntimeException("RustBuffer.alloc() returned null data pointer (size=${size})")
           }
        }

        internal fun create(capacity: ULong, len: ULong, data: Pointer?): RustBuffer.ByValue {
            var buf = RustBuffer.ByValue()
            buf.capacity = capacity.toLong()
            buf.len = len.toLong()
            buf.data = data
            return buf
        }

        internal fun free(buf: RustBuffer.ByValue) = uniffiRustCall() { status ->
            UniffiLib.INSTANCE.ffi_connector_ffi_uniffi_rustbuffer_free(buf, status)
        }
    }

    @Suppress("TooGenericExceptionThrown")
    fun asByteBuffer() =
        this.data?.getByteBuffer(0, this.len.toLong())?.also {
            it.order(ByteOrder.BIG_ENDIAN)
        }
}

/**
 * The equivalent of the `*mut RustBuffer` type.
 * Required for callbacks taking in an out pointer.
 *
 * Size is the sum of all values in the struct.
 *
 * @suppress
 */
class RustBufferByReference : ByReference(16) {
    /**
     * Set the pointed-to `RustBuffer` to the given value.
     */
    fun setValue(value: RustBuffer.ByValue) {
        // NOTE: The offsets are as they are in the C-like struct.
        val pointer = getPointer()
        pointer.setLong(0, value.capacity)
        pointer.setLong(8, value.len)
        pointer.setPointer(16, value.data)
    }

    /**
     * Get a `RustBuffer.ByValue` from this reference.
     */
    fun getValue(): RustBuffer.ByValue {
        val pointer = getPointer()
        val value = RustBuffer.ByValue()
        value.writeField("capacity", pointer.getLong(0))
        value.writeField("len", pointer.getLong(8))
        value.writeField("data", pointer.getLong(16))

        return value
    }
}

// This is a helper for safely passing byte references into the rust code.
// It's not actually used at the moment, because there aren't many things that you
// can take a direct pointer to in the JVM, and if we're going to copy something
// then we might as well copy it into a `RustBuffer`. But it's here for API
// completeness.

@Structure.FieldOrder("len", "data")
internal open class ForeignBytes : Structure() {
    @JvmField var len: Int = 0
    @JvmField var data: Pointer? = null

    class ByValue : ForeignBytes(), Structure.ByValue
}
/**
 * The FfiConverter interface handles converter types to and from the FFI
 *
 * All implementing objects should be public to support external types.  When a
 * type is external we need to import it's FfiConverter.
 *
 * @suppress
 */
public interface FfiConverter<KotlinType, FfiType> {
    // Convert an FFI type to a Kotlin type
    fun lift(value: FfiType): KotlinType

    // Convert an Kotlin type to an FFI type
    fun lower(value: KotlinType): FfiType

    // Read a Kotlin type from a `ByteBuffer`
    fun read(buf: ByteBuffer): KotlinType

    // Calculate bytes to allocate when creating a `RustBuffer`
    //
    // This must return at least as many bytes as the write() function will
    // write. It can return more bytes than needed, for example when writing
    // Strings we can't know the exact bytes needed until we the UTF-8
    // encoding, so we pessimistically allocate the largest size possible (3
    // bytes per codepoint).  Allocating extra bytes is not really a big deal
    // because the `RustBuffer` is short-lived.
    fun allocationSize(value: KotlinType): ULong

    // Write a Kotlin type to a `ByteBuffer`
    fun write(value: KotlinType, buf: ByteBuffer)

    // Lower a value into a `RustBuffer`
    //
    // This method lowers a value into a `RustBuffer` rather than the normal
    // FfiType.  It's used by the callback interface code.  Callback interface
    // returns are always serialized into a `RustBuffer` regardless of their
    // normal FFI type.
    fun lowerIntoRustBuffer(value: KotlinType): RustBuffer.ByValue {
        val rbuf = RustBuffer.alloc(allocationSize(value))
        try {
            val bbuf = rbuf.data!!.getByteBuffer(0, rbuf.capacity).also {
                it.order(ByteOrder.BIG_ENDIAN)
            }
            write(value, bbuf)
            rbuf.writeField("len", bbuf.position().toLong())
            return rbuf
        } catch (e: Throwable) {
            RustBuffer.free(rbuf)
            throw e
        }
    }

    // Lift a value from a `RustBuffer`.
    //
    // This here mostly because of the symmetry with `lowerIntoRustBuffer()`.
    // It's currently only used by the `FfiConverterRustBuffer` class below.
    fun liftFromRustBuffer(rbuf: RustBuffer.ByValue): KotlinType {
        val byteBuf = rbuf.asByteBuffer()!!
        try {
           val item = read(byteBuf)
           if (byteBuf.hasRemaining()) {
               throw RuntimeException("junk remaining in buffer after lifting, something is very wrong!!")
           }
           return item
        } finally {
            RustBuffer.free(rbuf)
        }
    }
}

/**
 * FfiConverter that uses `RustBuffer` as the FfiType
 *
 * @suppress
 */
public interface FfiConverterRustBuffer<KotlinType>: FfiConverter<KotlinType, RustBuffer.ByValue> {
    override fun lift(value: RustBuffer.ByValue) = liftFromRustBuffer(value)
    override fun lower(value: KotlinType) = lowerIntoRustBuffer(value)
}
// A handful of classes and functions to support the generated data structures.
// This would be a good candidate for isolating in its own ffi-support lib.

internal const val UNIFFI_CALL_SUCCESS = 0.toByte()
internal const val UNIFFI_CALL_ERROR = 1.toByte()
internal const val UNIFFI_CALL_UNEXPECTED_ERROR = 2.toByte()

@Structure.FieldOrder("code", "error_buf")
internal open class UniffiRustCallStatus : Structure() {
    @JvmField var code: Byte = 0
    @JvmField var error_buf: RustBuffer.ByValue = RustBuffer.ByValue()

    class ByValue: UniffiRustCallStatus(), Structure.ByValue

    fun isSuccess(): Boolean {
        return code == UNIFFI_CALL_SUCCESS
    }

    fun isError(): Boolean {
        return code == UNIFFI_CALL_ERROR
    }

    fun isPanic(): Boolean {
        return code == UNIFFI_CALL_UNEXPECTED_ERROR
    }

    companion object {
        fun create(code: Byte, errorBuf: RustBuffer.ByValue): UniffiRustCallStatus.ByValue {
            val callStatus = UniffiRustCallStatus.ByValue()
            callStatus.code = code
            callStatus.error_buf = errorBuf
            return callStatus
        }
    }
}

class InternalException(message: String) : kotlin.Exception(message)

/**
 * Each top-level error class has a companion object that can lift the error from the call status's rust buffer
 *
 * @suppress
 */
interface UniffiRustCallStatusErrorHandler<E> {
    fun lift(error_buf: RustBuffer.ByValue): E;
}

// Helpers for calling Rust
// In practice we usually need to be synchronized to call this safely, so it doesn't
// synchronize itself

// Call a rust function that returns a Result<>.  Pass in the Error class companion that corresponds to the Err
private inline fun <U, E: kotlin.Exception> uniffiRustCallWithError(errorHandler: UniffiRustCallStatusErrorHandler<E>, callback: (UniffiRustCallStatus) -> U): U {
    var status = UniffiRustCallStatus()
    val return_value = callback(status)
    uniffiCheckCallStatus(errorHandler, status)
    return return_value
}

// Check UniffiRustCallStatus and throw an error if the call wasn't successful
private fun<E: kotlin.Exception> uniffiCheckCallStatus(errorHandler: UniffiRustCallStatusErrorHandler<E>, status: UniffiRustCallStatus) {
    if (status.isSuccess()) {
        return
    } else if (status.isError()) {
        throw errorHandler.lift(status.error_buf)
    } else if (status.isPanic()) {
        // when the rust code sees a panic, it tries to construct a rustbuffer
        // with the message.  but if that code panics, then it just sends back
        // an empty buffer.
        if (status.error_buf.len > 0) {
            throw InternalException(FfiConverterString.lift(status.error_buf))
        } else {
            throw InternalException("Rust panic")
        }
    } else {
        throw InternalException("Unknown rust call status: $status.code")
    }
}

/**
 * UniffiRustCallStatusErrorHandler implementation for times when we don't expect a CALL_ERROR
 *
 * @suppress
 */
object UniffiNullRustCallStatusErrorHandler: UniffiRustCallStatusErrorHandler<InternalException> {
    override fun lift(error_buf: RustBuffer.ByValue): InternalException {
        RustBuffer.free(error_buf)
        return InternalException("Unexpected CALL_ERROR")
    }
}

// Call a rust function that returns a plain value
private inline fun <U> uniffiRustCall(callback: (UniffiRustCallStatus) -> U): U {
    return uniffiRustCallWithError(UniffiNullRustCallStatusErrorHandler, callback)
}

internal inline fun<T> uniffiTraitInterfaceCall(
    callStatus: UniffiRustCallStatus,
    makeCall: () -> T,
    writeReturn: (T) -> Unit,
) {
    try {
        writeReturn(makeCall())
    } catch(e: kotlin.Exception) {
        callStatus.code = UNIFFI_CALL_UNEXPECTED_ERROR
        callStatus.error_buf = FfiConverterString.lower(e.toString())
    }
}

internal inline fun<T, reified E: Throwable> uniffiTraitInterfaceCallWithError(
    callStatus: UniffiRustCallStatus,
    makeCall: () -> T,
    writeReturn: (T) -> Unit,
    lowerError: (E) -> RustBuffer.ByValue
) {
    try {
        writeReturn(makeCall())
    } catch(e: kotlin.Exception) {
        if (e is E) {
            callStatus.code = UNIFFI_CALL_ERROR
            callStatus.error_buf = lowerError(e)
        } else {
            callStatus.code = UNIFFI_CALL_UNEXPECTED_ERROR
            callStatus.error_buf = FfiConverterString.lower(e.toString())
        }
    }
}
// Map handles to objects
//
// This is used pass an opaque 64-bit handle representing a foreign object to the Rust code.
internal class UniffiHandleMap<T: Any> {
    private val map = ConcurrentHashMap<Long, T>()
    private val counter = java.util.concurrent.atomic.AtomicLong(0)

    val size: Int
        get() = map.size

    // Insert a new object into the handle map and get a handle for it
    fun insert(obj: T): Long {
        val handle = counter.getAndAdd(1)
        map.put(handle, obj)
        return handle
    }

    // Get an object from the handle map
    fun get(handle: Long): T {
        return map.get(handle) ?: throw InternalException("UniffiHandleMap.get: Invalid handle")
    }

    // Remove an entry from the handlemap and get the Kotlin object back
    fun remove(handle: Long): T {
        return map.remove(handle) ?: throw InternalException("UniffiHandleMap: Invalid handle")
    }
}

// Contains loading, initialization code,
// and the FFI Function declarations in a com.sun.jna.Library.
@Synchronized
private fun findLibraryName(componentName: String): String {
    val libOverride = System.getProperty("uniffi.component.$componentName.libraryOverride")
    if (libOverride != null) {
        return libOverride
    }
    return "connector_ffi_uniffi"
}

private inline fun <reified Lib : Library> loadIndirect(
    componentName: String
): Lib {
    return Native.load<Lib>(findLibraryName(componentName), Lib::class.java)
}

// Define FFI callback types
internal interface UniffiRustFutureContinuationCallback : com.sun.jna.Callback {
    fun callback(`data`: Long,`pollResult`: Byte,)
}
internal interface UniffiForeignFutureFree : com.sun.jna.Callback {
    fun callback(`handle`: Long,)
}
internal interface UniffiCallbackInterfaceFree : com.sun.jna.Callback {
    fun callback(`handle`: Long,)
}
@Structure.FieldOrder("handle", "free")
internal open class UniffiForeignFuture(
    @JvmField internal var `handle`: Long = 0.toLong(),
    @JvmField internal var `free`: UniffiForeignFutureFree? = null,
) : Structure() {
    class UniffiByValue(
        `handle`: Long = 0.toLong(),
        `free`: UniffiForeignFutureFree? = null,
    ): UniffiForeignFuture(`handle`,`free`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFuture) {
        `handle` = other.`handle`
        `free` = other.`free`
    }

}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureStructU8(
    @JvmField internal var `returnValue`: Byte = 0.toByte(),
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: Byte = 0.toByte(),
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureStructU8(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureStructU8) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteU8 : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureStructU8.UniffiByValue,)
}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureStructI8(
    @JvmField internal var `returnValue`: Byte = 0.toByte(),
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: Byte = 0.toByte(),
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureStructI8(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureStructI8) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteI8 : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureStructI8.UniffiByValue,)
}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureStructU16(
    @JvmField internal var `returnValue`: Short = 0.toShort(),
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: Short = 0.toShort(),
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureStructU16(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureStructU16) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteU16 : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureStructU16.UniffiByValue,)
}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureStructI16(
    @JvmField internal var `returnValue`: Short = 0.toShort(),
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: Short = 0.toShort(),
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureStructI16(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureStructI16) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteI16 : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureStructI16.UniffiByValue,)
}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureStructU32(
    @JvmField internal var `returnValue`: Int = 0,
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: Int = 0,
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureStructU32(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureStructU32) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteU32 : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureStructU32.UniffiByValue,)
}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureStructI32(
    @JvmField internal var `returnValue`: Int = 0,
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: Int = 0,
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureStructI32(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureStructI32) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteI32 : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureStructI32.UniffiByValue,)
}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureStructU64(
    @JvmField internal var `returnValue`: Long = 0.toLong(),
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: Long = 0.toLong(),
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureStructU64(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureStructU64) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteU64 : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureStructU64.UniffiByValue,)
}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureStructI64(
    @JvmField internal var `returnValue`: Long = 0.toLong(),
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: Long = 0.toLong(),
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureStructI64(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureStructI64) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteI64 : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureStructI64.UniffiByValue,)
}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureStructF32(
    @JvmField internal var `returnValue`: Float = 0.0f,
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: Float = 0.0f,
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureStructF32(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureStructF32) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteF32 : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureStructF32.UniffiByValue,)
}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureStructF64(
    @JvmField internal var `returnValue`: Double = 0.0,
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: Double = 0.0,
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureStructF64(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureStructF64) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteF64 : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureStructF64.UniffiByValue,)
}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureStructPointer(
    @JvmField internal var `returnValue`: Pointer = Pointer.NULL,
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: Pointer = Pointer.NULL,
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureStructPointer(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureStructPointer) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompletePointer : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureStructPointer.UniffiByValue,)
}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureStructRustBuffer(
    @JvmField internal var `returnValue`: RustBuffer.ByValue = RustBuffer.ByValue(),
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: RustBuffer.ByValue = RustBuffer.ByValue(),
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureStructRustBuffer(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureStructRustBuffer) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteRustBuffer : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureStructRustBuffer.UniffiByValue,)
}
@Structure.FieldOrder("callStatus")
internal open class UniffiForeignFutureStructVoid(
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureStructVoid(`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureStructVoid) {
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteVoid : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureStructVoid.UniffiByValue,)
}
















































































// A JNA Library to expose the extern-C FFI definitions.
// This is an implementation detail which will be called internally by the public API.

internal interface UniffiLib : Library {
    companion object {
        internal val INSTANCE: UniffiLib by lazy {
            loadIndirect<UniffiLib>(componentName = "connector_ffi_uniffi")
            .also { lib: UniffiLib ->
                uniffiCheckContractApiVersion(lib)
                uniffiCheckApiChecksums(lib)
                }
        }
        
        // The Cleaner for the whole library
        internal val CLEANER: UniffiCleaner by lazy {
            UniffiCleaner.create()
        }
    }

    fun uniffi_connector_ffi_uniffi_fn_clone_connectorregistry(`ptr`: Pointer,uniffi_out_err: UniffiRustCallStatus, 
    ): Pointer
    fun uniffi_connector_ffi_uniffi_fn_free_connectorregistry(`ptr`: Pointer,uniffi_out_err: UniffiRustCallStatus, 
    ): Unit
    fun uniffi_connector_ffi_uniffi_fn_constructor_connectorregistry_new(uniffi_out_err: UniffiRustCallStatus, 
    ): Pointer
    fun uniffi_connector_ffi_uniffi_fn_method_connectorregistry_get_connector_info(`ptr`: Pointer,`name`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    fun uniffi_connector_ffi_uniffi_fn_method_connectorregistry_get_supported_flows(`ptr`: Pointer,`name`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    fun uniffi_connector_ffi_uniffi_fn_method_connectorregistry_list_connectors(`ptr`: Pointer,uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    fun uniffi_connector_ffi_uniffi_fn_func_create_card_payment_method(`number`: RustBuffer.ByValue,`expMonth`: Int,`expYear`: Int,`cvc`: RustBuffer.ByValue,`holderName`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    fun uniffi_connector_ffi_uniffi_fn_func_create_wallet_payment_method(`walletType`: RustBuffer.ByValue,`token`: RustBuffer.ByValue,`email`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    fun uniffi_connector_ffi_uniffi_fn_func_get_connector_info(`name`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    fun uniffi_connector_ffi_uniffi_fn_func_list_supported_connectors(uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    fun uniffi_connector_ffi_uniffi_fn_func_transform_request(`input`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    fun uniffi_connector_ffi_uniffi_fn_func_transform_response(`input`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    fun ffi_connector_ffi_uniffi_rustbuffer_alloc(`size`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    fun ffi_connector_ffi_uniffi_rustbuffer_from_bytes(`bytes`: ForeignBytes.ByValue,uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    fun ffi_connector_ffi_uniffi_rustbuffer_free(`buf`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus, 
    ): Unit
    fun ffi_connector_ffi_uniffi_rustbuffer_reserve(`buf`: RustBuffer.ByValue,`additional`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    fun ffi_connector_ffi_uniffi_rust_future_poll_u8(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
    ): Unit
    fun ffi_connector_ffi_uniffi_rust_future_cancel_u8(`handle`: Long,
    ): Unit
    fun ffi_connector_ffi_uniffi_rust_future_free_u8(`handle`: Long,
    ): Unit
    fun ffi_connector_ffi_uniffi_rust_future_complete_u8(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): Byte
    fun ffi_connector_ffi_uniffi_rust_future_poll_i8(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
    ): Unit
    fun ffi_connector_ffi_uniffi_rust_future_cancel_i8(`handle`: Long,
    ): Unit
    fun ffi_connector_ffi_uniffi_rust_future_free_i8(`handle`: Long,
    ): Unit
    fun ffi_connector_ffi_uniffi_rust_future_complete_i8(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): Byte
    fun ffi_connector_ffi_uniffi_rust_future_poll_u16(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
    ): Unit
    fun ffi_connector_ffi_uniffi_rust_future_cancel_u16(`handle`: Long,
    ): Unit
    fun ffi_connector_ffi_uniffi_rust_future_free_u16(`handle`: Long,
    ): Unit
    fun ffi_connector_ffi_uniffi_rust_future_complete_u16(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): Short
    fun ffi_connector_ffi_uniffi_rust_future_poll_i16(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
    ): Unit
    fun ffi_connector_ffi_uniffi_rust_future_cancel_i16(`handle`: Long,
    ): Unit
    fun ffi_connector_ffi_uniffi_rust_future_free_i16(`handle`: Long,
    ): Unit
    fun ffi_connector_ffi_uniffi_rust_future_complete_i16(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): Short
    fun ffi_connector_ffi_uniffi_rust_future_poll_u32(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
    ): Unit
    fun ffi_connector_ffi_uniffi_rust_future_cancel_u32(`handle`: Long,
    ): Unit
    fun ffi_connector_ffi_uniffi_rust_future_free_u32(`handle`: Long,
    ): Unit
    fun ffi_connector_ffi_uniffi_rust_future_complete_u32(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): Int
    fun ffi_connector_ffi_uniffi_rust_future_poll_i32(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
    ): Unit
    fun ffi_connector_ffi_uniffi_rust_future_cancel_i32(`handle`: Long,
    ): Unit
    fun ffi_connector_ffi_uniffi_rust_future_free_i32(`handle`: Long,
    ): Unit
    fun ffi_connector_ffi_uniffi_rust_future_complete_i32(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): Int
    fun ffi_connector_ffi_uniffi_rust_future_poll_u64(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
    ): Unit
    fun ffi_connector_ffi_uniffi_rust_future_cancel_u64(`handle`: Long,
    ): Unit
    fun ffi_connector_ffi_uniffi_rust_future_free_u64(`handle`: Long,
    ): Unit
    fun ffi_connector_ffi_uniffi_rust_future_complete_u64(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): Long
    fun ffi_connector_ffi_uniffi_rust_future_poll_i64(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
    ): Unit
    fun ffi_connector_ffi_uniffi_rust_future_cancel_i64(`handle`: Long,
    ): Unit
    fun ffi_connector_ffi_uniffi_rust_future_free_i64(`handle`: Long,
    ): Unit
    fun ffi_connector_ffi_uniffi_rust_future_complete_i64(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): Long
    fun ffi_connector_ffi_uniffi_rust_future_poll_f32(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
    ): Unit
    fun ffi_connector_ffi_uniffi_rust_future_cancel_f32(`handle`: Long,
    ): Unit
    fun ffi_connector_ffi_uniffi_rust_future_free_f32(`handle`: Long,
    ): Unit
    fun ffi_connector_ffi_uniffi_rust_future_complete_f32(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): Float
    fun ffi_connector_ffi_uniffi_rust_future_poll_f64(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
    ): Unit
    fun ffi_connector_ffi_uniffi_rust_future_cancel_f64(`handle`: Long,
    ): Unit
    fun ffi_connector_ffi_uniffi_rust_future_free_f64(`handle`: Long,
    ): Unit
    fun ffi_connector_ffi_uniffi_rust_future_complete_f64(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): Double
    fun ffi_connector_ffi_uniffi_rust_future_poll_pointer(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
    ): Unit
    fun ffi_connector_ffi_uniffi_rust_future_cancel_pointer(`handle`: Long,
    ): Unit
    fun ffi_connector_ffi_uniffi_rust_future_free_pointer(`handle`: Long,
    ): Unit
    fun ffi_connector_ffi_uniffi_rust_future_complete_pointer(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): Pointer
    fun ffi_connector_ffi_uniffi_rust_future_poll_rust_buffer(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
    ): Unit
    fun ffi_connector_ffi_uniffi_rust_future_cancel_rust_buffer(`handle`: Long,
    ): Unit
    fun ffi_connector_ffi_uniffi_rust_future_free_rust_buffer(`handle`: Long,
    ): Unit
    fun ffi_connector_ffi_uniffi_rust_future_complete_rust_buffer(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    fun ffi_connector_ffi_uniffi_rust_future_poll_void(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
    ): Unit
    fun ffi_connector_ffi_uniffi_rust_future_cancel_void(`handle`: Long,
    ): Unit
    fun ffi_connector_ffi_uniffi_rust_future_free_void(`handle`: Long,
    ): Unit
    fun ffi_connector_ffi_uniffi_rust_future_complete_void(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): Unit
    fun uniffi_connector_ffi_uniffi_checksum_func_create_card_payment_method(
    ): Short
    fun uniffi_connector_ffi_uniffi_checksum_func_create_wallet_payment_method(
    ): Short
    fun uniffi_connector_ffi_uniffi_checksum_func_get_connector_info(
    ): Short
    fun uniffi_connector_ffi_uniffi_checksum_func_list_supported_connectors(
    ): Short
    fun uniffi_connector_ffi_uniffi_checksum_func_transform_request(
    ): Short
    fun uniffi_connector_ffi_uniffi_checksum_func_transform_response(
    ): Short
    fun uniffi_connector_ffi_uniffi_checksum_method_connectorregistry_get_connector_info(
    ): Short
    fun uniffi_connector_ffi_uniffi_checksum_method_connectorregistry_get_supported_flows(
    ): Short
    fun uniffi_connector_ffi_uniffi_checksum_method_connectorregistry_list_connectors(
    ): Short
    fun uniffi_connector_ffi_uniffi_checksum_constructor_connectorregistry_new(
    ): Short
    fun ffi_connector_ffi_uniffi_uniffi_contract_version(
    ): Int
    
}

private fun uniffiCheckContractApiVersion(lib: UniffiLib) {
    // Get the bindings contract version from our ComponentInterface
    val bindings_contract_version = 26
    // Get the scaffolding contract version by calling the into the dylib
    val scaffolding_contract_version = lib.ffi_connector_ffi_uniffi_uniffi_contract_version()
    if (bindings_contract_version != scaffolding_contract_version) {
        throw RuntimeException("UniFFI contract version mismatch: try cleaning and rebuilding your project")
    }
}

@Suppress("UNUSED_PARAMETER")
private fun uniffiCheckApiChecksums(lib: UniffiLib) {
    if (lib.uniffi_connector_ffi_uniffi_checksum_func_create_card_payment_method() != 48247.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_connector_ffi_uniffi_checksum_func_create_wallet_payment_method() != 16346.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_connector_ffi_uniffi_checksum_func_get_connector_info() != 15403.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_connector_ffi_uniffi_checksum_func_list_supported_connectors() != 15737.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_connector_ffi_uniffi_checksum_func_transform_request() != 27374.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_connector_ffi_uniffi_checksum_func_transform_response() != 30938.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_connector_ffi_uniffi_checksum_method_connectorregistry_get_connector_info() != 45843.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_connector_ffi_uniffi_checksum_method_connectorregistry_get_supported_flows() != 23769.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_connector_ffi_uniffi_checksum_method_connectorregistry_list_connectors() != 50654.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_connector_ffi_uniffi_checksum_constructor_connectorregistry_new() != 7068.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
}

// Async support

// Public interface members begin here.


// Interface implemented by anything that can contain an object reference.
//
// Such types expose a `destroy()` method that must be called to cleanly
// dispose of the contained objects. Failure to call this method may result
// in memory leaks.
//
// The easiest way to ensure this method is called is to use the `.use`
// helper method to execute a block and destroy the object at the end.
interface Disposable {
    fun destroy()
    companion object {
        fun destroy(vararg args: Any?) {
            args.filterIsInstance<Disposable>()
                .forEach(Disposable::destroy)
        }
    }
}

/**
 * @suppress
 */
inline fun <T : Disposable?, R> T.use(block: (T) -> R) =
    try {
        block(this)
    } finally {
        try {
            // N.B. our implementation is on the nullable type `Disposable?`.
            this?.destroy()
        } catch (e: Throwable) {
            // swallow
        }
    }

/** 
 * Used to instantiate an interface without an actual pointer, for fakes in tests, mostly.
 *
 * @suppress
 * */
object NoPointer

/**
 * @suppress
 */
public object FfiConverterUShort: FfiConverter<UShort, Short> {
    override fun lift(value: Short): UShort {
        return value.toUShort()
    }

    override fun read(buf: ByteBuffer): UShort {
        return lift(buf.getShort())
    }

    override fun lower(value: UShort): Short {
        return value.toShort()
    }

    override fun allocationSize(value: UShort) = 2UL

    override fun write(value: UShort, buf: ByteBuffer) {
        buf.putShort(value.toShort())
    }
}

/**
 * @suppress
 */
public object FfiConverterUInt: FfiConverter<UInt, Int> {
    override fun lift(value: Int): UInt {
        return value.toUInt()
    }

    override fun read(buf: ByteBuffer): UInt {
        return lift(buf.getInt())
    }

    override fun lower(value: UInt): Int {
        return value.toInt()
    }

    override fun allocationSize(value: UInt) = 4UL

    override fun write(value: UInt, buf: ByteBuffer) {
        buf.putInt(value.toInt())
    }
}

/**
 * @suppress
 */
public object FfiConverterLong: FfiConverter<Long, Long> {
    override fun lift(value: Long): Long {
        return value
    }

    override fun read(buf: ByteBuffer): Long {
        return buf.getLong()
    }

    override fun lower(value: Long): Long {
        return value
    }

    override fun allocationSize(value: Long) = 8UL

    override fun write(value: Long, buf: ByteBuffer) {
        buf.putLong(value)
    }
}

/**
 * @suppress
 */
public object FfiConverterBoolean: FfiConverter<Boolean, Byte> {
    override fun lift(value: Byte): Boolean {
        return value.toInt() != 0
    }

    override fun read(buf: ByteBuffer): Boolean {
        return lift(buf.get())
    }

    override fun lower(value: Boolean): Byte {
        return if (value) 1.toByte() else 0.toByte()
    }

    override fun allocationSize(value: Boolean) = 1UL

    override fun write(value: Boolean, buf: ByteBuffer) {
        buf.put(lower(value))
    }
}

/**
 * @suppress
 */
public object FfiConverterString: FfiConverter<String, RustBuffer.ByValue> {
    // Note: we don't inherit from FfiConverterRustBuffer, because we use a
    // special encoding when lowering/lifting.  We can use `RustBuffer.len` to
    // store our length and avoid writing it out to the buffer.
    override fun lift(value: RustBuffer.ByValue): String {
        try {
            val byteArr = ByteArray(value.len.toInt())
            value.asByteBuffer()!!.get(byteArr)
            return byteArr.toString(Charsets.UTF_8)
        } finally {
            RustBuffer.free(value)
        }
    }

    override fun read(buf: ByteBuffer): String {
        val len = buf.getInt()
        val byteArr = ByteArray(len)
        buf.get(byteArr)
        return byteArr.toString(Charsets.UTF_8)
    }

    fun toUtf8(value: String): ByteBuffer {
        // Make sure we don't have invalid UTF-16, check for lone surrogates.
        return Charsets.UTF_8.newEncoder().run {
            onMalformedInput(CodingErrorAction.REPORT)
            encode(CharBuffer.wrap(value))
        }
    }

    override fun lower(value: String): RustBuffer.ByValue {
        val byteBuf = toUtf8(value)
        // Ideally we'd pass these bytes to `ffi_bytebuffer_from_bytes`, but doing so would require us
        // to copy them into a JNA `Memory`. So we might as well directly copy them into a `RustBuffer`.
        val rbuf = RustBuffer.alloc(byteBuf.limit().toULong())
        rbuf.asByteBuffer()!!.put(byteBuf)
        return rbuf
    }

    // We aren't sure exactly how many bytes our string will be once it's UTF-8
    // encoded.  Allocate 3 bytes per UTF-16 code unit which will always be
    // enough.
    override fun allocationSize(value: String): ULong {
        val sizeForLength = 4UL
        val sizeForString = value.length.toULong() * 3UL
        return sizeForLength + sizeForString
    }

    override fun write(value: String, buf: ByteBuffer) {
        val byteBuf = toUtf8(value)
        buf.putInt(byteBuf.limit())
        buf.put(byteBuf)
    }
}


// This template implements a class for working with a Rust struct via a Pointer/Arc<T>
// to the live Rust struct on the other side of the FFI.
//
// Each instance implements core operations for working with the Rust `Arc<T>` and the
// Kotlin Pointer to work with the live Rust struct on the other side of the FFI.
//
// There's some subtlety here, because we have to be careful not to operate on a Rust
// struct after it has been dropped, and because we must expose a public API for freeing
// theq Kotlin wrapper object in lieu of reliable finalizers. The core requirements are:
//
//   * Each instance holds an opaque pointer to the underlying Rust struct.
//     Method calls need to read this pointer from the object's state and pass it in to
//     the Rust FFI.
//
//   * When an instance is no longer needed, its pointer should be passed to a
//     special destructor function provided by the Rust FFI, which will drop the
//     underlying Rust struct.
//
//   * Given an instance, calling code is expected to call the special
//     `destroy` method in order to free it after use, either by calling it explicitly
//     or by using a higher-level helper like the `use` method. Failing to do so risks
//     leaking the underlying Rust struct.
//
//   * We can't assume that calling code will do the right thing, and must be prepared
//     to handle Kotlin method calls executing concurrently with or even after a call to
//     `destroy`, and to handle multiple (possibly concurrent!) calls to `destroy`.
//
//   * We must never allow Rust code to operate on the underlying Rust struct after
//     the destructor has been called, and must never call the destructor more than once.
//     Doing so may trigger memory unsafety.
//
//   * To mitigate many of the risks of leaking memory and use-after-free unsafety, a `Cleaner`
//     is implemented to call the destructor when the Kotlin object becomes unreachable.
//     This is done in a background thread. This is not a panacea, and client code should be aware that
//      1. the thread may starve if some there are objects that have poorly performing
//     `drop` methods or do significant work in their `drop` methods.
//      2. the thread is shared across the whole library. This can be tuned by using `android_cleaner = true`,
//         or `android = true` in the [`kotlin` section of the `uniffi.toml` file](https://mozilla.github.io/uniffi-rs/kotlin/configuration.html).
//
// If we try to implement this with mutual exclusion on access to the pointer, there is the
// possibility of a race between a method call and a concurrent call to `destroy`:
//
//    * Thread A starts a method call, reads the value of the pointer, but is interrupted
//      before it can pass the pointer over the FFI to Rust.
//    * Thread B calls `destroy` and frees the underlying Rust struct.
//    * Thread A resumes, passing the already-read pointer value to Rust and triggering
//      a use-after-free.
//
// One possible solution would be to use a `ReadWriteLock`, with each method call taking
// a read lock (and thus allowed to run concurrently) and the special `destroy` method
// taking a write lock (and thus blocking on live method calls). However, we aim not to
// generate methods with any hidden blocking semantics, and a `destroy` method that might
// block if called incorrectly seems to meet that bar.
//
// So, we achieve our goals by giving each instance an associated `AtomicLong` counter to track
// the number of in-flight method calls, and an `AtomicBoolean` flag to indicate whether `destroy`
// has been called. These are updated according to the following rules:
//
//    * The initial value of the counter is 1, indicating a live object with no in-flight calls.
//      The initial value for the flag is false.
//
//    * At the start of each method call, we atomically check the counter.
//      If it is 0 then the underlying Rust struct has already been destroyed and the call is aborted.
//      If it is nonzero them we atomically increment it by 1 and proceed with the method call.
//
//    * At the end of each method call, we atomically decrement and check the counter.
//      If it has reached zero then we destroy the underlying Rust struct.
//
//    * When `destroy` is called, we atomically flip the flag from false to true.
//      If the flag was already true we silently fail.
//      Otherwise we atomically decrement and check the counter.
//      If it has reached zero then we destroy the underlying Rust struct.
//
// Astute readers may observe that this all sounds very similar to the way that Rust's `Arc<T>` works,
// and indeed it is, with the addition of a flag to guard against multiple calls to `destroy`.
//
// The overall effect is that the underlying Rust struct is destroyed only when `destroy` has been
// called *and* all in-flight method calls have completed, avoiding violating any of the expectations
// of the underlying Rust code.
//
// This makes a cleaner a better alternative to _not_ calling `destroy()` as
// and when the object is finished with, but the abstraction is not perfect: if the Rust object's `drop`
// method is slow, and/or there are many objects to cleanup, and it's on a low end Android device, then the cleaner
// thread may be starved, and the app will leak memory.
//
// In this case, `destroy`ing manually may be a better solution.
//
// The cleaner can live side by side with the manual calling of `destroy`. In the order of responsiveness, uniffi objects
// with Rust peers are reclaimed:
//
// 1. By calling the `destroy` method of the object, which calls `rustObject.free()`. If that doesn't happen:
// 2. When the object becomes unreachable, AND the Cleaner thread gets to call `rustObject.free()`. If the thread is starved then:
// 3. The memory is reclaimed when the process terminates.
//
// [1] https://stackoverflow.com/questions/24376768/can-java-finalize-an-object-when-it-is-still-in-scope/24380219
//


/**
 * The cleaner interface for Object finalization code to run.
 * This is the entry point to any implementation that we're using.
 *
 * The cleaner registers objects and returns cleanables, so now we are
 * defining a `UniffiCleaner` with a `UniffiClenaer.Cleanable` to abstract the
 * different implmentations available at compile time.
 *
 * @suppress
 */
interface UniffiCleaner {
    interface Cleanable {
        fun clean()
    }

    fun register(value: Any, cleanUpTask: Runnable): UniffiCleaner.Cleanable

    companion object
}

// The fallback Jna cleaner, which is available for both Android, and the JVM.
private class UniffiJnaCleaner : UniffiCleaner {
    private val cleaner = com.sun.jna.internal.Cleaner.getCleaner()

    override fun register(value: Any, cleanUpTask: Runnable): UniffiCleaner.Cleanable =
        UniffiJnaCleanable(cleaner.register(value, cleanUpTask))
}

private class UniffiJnaCleanable(
    private val cleanable: com.sun.jna.internal.Cleaner.Cleanable,
) : UniffiCleaner.Cleanable {
    override fun clean() = cleanable.clean()
}

// We decide at uniffi binding generation time whether we were
// using Android or not.
// There are further runtime checks to chose the correct implementation
// of the cleaner.
private fun UniffiCleaner.Companion.create(): UniffiCleaner =
    try {
        // For safety's sake: if the library hasn't been run in android_cleaner = true
        // mode, but is being run on Android, then we still need to think about
        // Android API versions.
        // So we check if java.lang.ref.Cleaner is there, and use that…
        java.lang.Class.forName("java.lang.ref.Cleaner")
        JavaLangRefCleaner()
    } catch (e: ClassNotFoundException) {
        // … otherwise, fallback to the JNA cleaner.
        UniffiJnaCleaner()
    }

private class JavaLangRefCleaner : UniffiCleaner {
    val cleaner = java.lang.ref.Cleaner.create()

    override fun register(value: Any, cleanUpTask: Runnable): UniffiCleaner.Cleanable =
        JavaLangRefCleanable(cleaner.register(value, cleanUpTask))
}

private class JavaLangRefCleanable(
    val cleanable: java.lang.ref.Cleaner.Cleanable
) : UniffiCleaner.Cleanable {
    override fun clean() = cleanable.clean()
}
public interface ConnectorRegistryInterface {
    
    fun `getConnectorInfo`(`name`: kotlin.String): ConnectorInfo?
    
    fun `getSupportedFlows`(`name`: kotlin.String): List<PaymentFlow>
    
    fun `listConnectors`(): List<kotlin.String>
    
    companion object
}

open class ConnectorRegistry: Disposable, AutoCloseable, ConnectorRegistryInterface {

    constructor(pointer: Pointer) {
        this.pointer = pointer
        this.cleanable = UniffiLib.CLEANER.register(this, UniffiCleanAction(pointer))
    }

    /**
     * This constructor can be used to instantiate a fake object. Only used for tests. Any
     * attempt to actually use an object constructed this way will fail as there is no
     * connected Rust object.
     */
    @Suppress("UNUSED_PARAMETER")
    constructor(noPointer: NoPointer) {
        this.pointer = null
        this.cleanable = UniffiLib.CLEANER.register(this, UniffiCleanAction(pointer))
    }
    constructor() :
        this(
    uniffiRustCall() { _status ->
    UniffiLib.INSTANCE.uniffi_connector_ffi_uniffi_fn_constructor_connectorregistry_new(
        _status)
}
    )

    protected val pointer: Pointer?
    protected val cleanable: UniffiCleaner.Cleanable

    private val wasDestroyed = AtomicBoolean(false)
    private val callCounter = AtomicLong(1)

    override fun destroy() {
        // Only allow a single call to this method.
        // TODO: maybe we should log a warning if called more than once?
        if (this.wasDestroyed.compareAndSet(false, true)) {
            // This decrement always matches the initial count of 1 given at creation time.
            if (this.callCounter.decrementAndGet() == 0L) {
                cleanable.clean()
            }
        }
    }

    @Synchronized
    override fun close() {
        this.destroy()
    }

    internal inline fun <R> callWithPointer(block: (ptr: Pointer) -> R): R {
        // Check and increment the call counter, to keep the object alive.
        // This needs a compare-and-set retry loop in case of concurrent updates.
        do {
            val c = this.callCounter.get()
            if (c == 0L) {
                throw IllegalStateException("${this.javaClass.simpleName} object has already been destroyed")
            }
            if (c == Long.MAX_VALUE) {
                throw IllegalStateException("${this.javaClass.simpleName} call counter would overflow")
            }
        } while (! this.callCounter.compareAndSet(c, c + 1L))
        // Now we can safely do the method call without the pointer being freed concurrently.
        try {
            return block(this.uniffiClonePointer())
        } finally {
            // This decrement always matches the increment we performed above.
            if (this.callCounter.decrementAndGet() == 0L) {
                cleanable.clean()
            }
        }
    }

    // Use a static inner class instead of a closure so as not to accidentally
    // capture `this` as part of the cleanable's action.
    private class UniffiCleanAction(private val pointer: Pointer?) : Runnable {
        override fun run() {
            pointer?.let { ptr ->
                uniffiRustCall { status ->
                    UniffiLib.INSTANCE.uniffi_connector_ffi_uniffi_fn_free_connectorregistry(ptr, status)
                }
            }
        }
    }

    fun uniffiClonePointer(): Pointer {
        return uniffiRustCall() { status ->
            UniffiLib.INSTANCE.uniffi_connector_ffi_uniffi_fn_clone_connectorregistry(pointer!!, status)
        }
    }

    override fun `getConnectorInfo`(`name`: kotlin.String): ConnectorInfo? {
            return FfiConverterOptionalTypeConnectorInfo.lift(
    callWithPointer {
    uniffiRustCall() { _status ->
    UniffiLib.INSTANCE.uniffi_connector_ffi_uniffi_fn_method_connectorregistry_get_connector_info(
        it, FfiConverterString.lower(`name`),_status)
}
    }
    )
    }
    

    
    @Throws(ConnectorException::class)override fun `getSupportedFlows`(`name`: kotlin.String): List<PaymentFlow> {
            return FfiConverterSequenceTypePaymentFlow.lift(
    callWithPointer {
    uniffiRustCallWithError(ConnectorException) { _status ->
    UniffiLib.INSTANCE.uniffi_connector_ffi_uniffi_fn_method_connectorregistry_get_supported_flows(
        it, FfiConverterString.lower(`name`),_status)
}
    }
    )
    }
    

    override fun `listConnectors`(): List<kotlin.String> {
            return FfiConverterSequenceString.lift(
    callWithPointer {
    uniffiRustCall() { _status ->
    UniffiLib.INSTANCE.uniffi_connector_ffi_uniffi_fn_method_connectorregistry_list_connectors(
        it, _status)
}
    }
    )
    }
    

    

    
    
    companion object
    
}

/**
 * @suppress
 */
public object FfiConverterTypeConnectorRegistry: FfiConverter<ConnectorRegistry, Pointer> {

    override fun lower(value: ConnectorRegistry): Pointer {
        return value.uniffiClonePointer()
    }

    override fun lift(value: Pointer): ConnectorRegistry {
        return ConnectorRegistry(value)
    }

    override fun read(buf: ByteBuffer): ConnectorRegistry {
        // The Rust code always writes pointers as 8 bytes, and will
        // fail to compile if they don't fit.
        return lift(Pointer(buf.getLong()))
    }

    override fun allocationSize(value: ConnectorRegistry) = 8UL

    override fun write(value: ConnectorRegistry, buf: ByteBuffer) {
        // The Rust code always expects pointers written as 8 bytes,
        // and will fail to compile if they don't fit.
        buf.putLong(Pointer.nativeValue(lower(value)))
    }
}



data class BankTransferData (
    val `bankName`: kotlin.String?, 
    val `accountNumber`: kotlin.String?, 
    val `routingNumber`: kotlin.String?, 
    val `iban`: kotlin.String?, 
    val `bic`: kotlin.String?
) {
    
    companion object
}

/**
 * @suppress
 */
public object FfiConverterTypeBankTransferData: FfiConverterRustBuffer<BankTransferData> {
    override fun read(buf: ByteBuffer): BankTransferData {
        return BankTransferData(
            FfiConverterOptionalString.read(buf),
            FfiConverterOptionalString.read(buf),
            FfiConverterOptionalString.read(buf),
            FfiConverterOptionalString.read(buf),
            FfiConverterOptionalString.read(buf),
        )
    }

    override fun allocationSize(value: BankTransferData) = (
            FfiConverterOptionalString.allocationSize(value.`bankName`) +
            FfiConverterOptionalString.allocationSize(value.`accountNumber`) +
            FfiConverterOptionalString.allocationSize(value.`routingNumber`) +
            FfiConverterOptionalString.allocationSize(value.`iban`) +
            FfiConverterOptionalString.allocationSize(value.`bic`)
    )

    override fun write(value: BankTransferData, buf: ByteBuffer) {
            FfiConverterOptionalString.write(value.`bankName`, buf)
            FfiConverterOptionalString.write(value.`accountNumber`, buf)
            FfiConverterOptionalString.write(value.`routingNumber`, buf)
            FfiConverterOptionalString.write(value.`iban`, buf)
            FfiConverterOptionalString.write(value.`bic`, buf)
    }
}



data class CardData (
    val `number`: kotlin.String, 
    val `expMonth`: kotlin.UInt, 
    val `expYear`: kotlin.UInt, 
    val `cvc`: kotlin.String, 
    val `holderName`: kotlin.String?
) {
    
    companion object
}

/**
 * @suppress
 */
public object FfiConverterTypeCardData: FfiConverterRustBuffer<CardData> {
    override fun read(buf: ByteBuffer): CardData {
        return CardData(
            FfiConverterString.read(buf),
            FfiConverterUInt.read(buf),
            FfiConverterUInt.read(buf),
            FfiConverterString.read(buf),
            FfiConverterOptionalString.read(buf),
        )
    }

    override fun allocationSize(value: CardData) = (
            FfiConverterString.allocationSize(value.`number`) +
            FfiConverterUInt.allocationSize(value.`expMonth`) +
            FfiConverterUInt.allocationSize(value.`expYear`) +
            FfiConverterString.allocationSize(value.`cvc`) +
            FfiConverterOptionalString.allocationSize(value.`holderName`)
    )

    override fun write(value: CardData, buf: ByteBuffer) {
            FfiConverterString.write(value.`number`, buf)
            FfiConverterUInt.write(value.`expMonth`, buf)
            FfiConverterUInt.write(value.`expYear`, buf)
            FfiConverterString.write(value.`cvc`, buf)
            FfiConverterOptionalString.write(value.`holderName`, buf)
    }
}



data class ConnectorInfo (
    val `name`: kotlin.String, 
    val `displayName`: kotlin.String, 
    val `baseUrl`: kotlin.String, 
    val `authType`: AuthType, 
    val `authFields`: List<kotlin.String>, 
    val `supportedFlows`: List<PaymentFlow>, 
    val `supportedCurrencies`: List<kotlin.String>, 
    val `bodyFormat`: BodyFormat, 
    val `supportsWebhooks`: kotlin.Boolean, 
    val `supports3ds`: kotlin.Boolean
) {
    
    companion object
}

/**
 * @suppress
 */
public object FfiConverterTypeConnectorInfo: FfiConverterRustBuffer<ConnectorInfo> {
    override fun read(buf: ByteBuffer): ConnectorInfo {
        return ConnectorInfo(
            FfiConverterString.read(buf),
            FfiConverterString.read(buf),
            FfiConverterString.read(buf),
            FfiConverterTypeAuthType.read(buf),
            FfiConverterSequenceString.read(buf),
            FfiConverterSequenceTypePaymentFlow.read(buf),
            FfiConverterSequenceString.read(buf),
            FfiConverterTypeBodyFormat.read(buf),
            FfiConverterBoolean.read(buf),
            FfiConverterBoolean.read(buf),
        )
    }

    override fun allocationSize(value: ConnectorInfo) = (
            FfiConverterString.allocationSize(value.`name`) +
            FfiConverterString.allocationSize(value.`displayName`) +
            FfiConverterString.allocationSize(value.`baseUrl`) +
            FfiConverterTypeAuthType.allocationSize(value.`authType`) +
            FfiConverterSequenceString.allocationSize(value.`authFields`) +
            FfiConverterSequenceTypePaymentFlow.allocationSize(value.`supportedFlows`) +
            FfiConverterSequenceString.allocationSize(value.`supportedCurrencies`) +
            FfiConverterTypeBodyFormat.allocationSize(value.`bodyFormat`) +
            FfiConverterBoolean.allocationSize(value.`supportsWebhooks`) +
            FfiConverterBoolean.allocationSize(value.`supports3ds`)
    )

    override fun write(value: ConnectorInfo, buf: ByteBuffer) {
            FfiConverterString.write(value.`name`, buf)
            FfiConverterString.write(value.`displayName`, buf)
            FfiConverterString.write(value.`baseUrl`, buf)
            FfiConverterTypeAuthType.write(value.`authType`, buf)
            FfiConverterSequenceString.write(value.`authFields`, buf)
            FfiConverterSequenceTypePaymentFlow.write(value.`supportedFlows`, buf)
            FfiConverterSequenceString.write(value.`supportedCurrencies`, buf)
            FfiConverterTypeBodyFormat.write(value.`bodyFormat`, buf)
            FfiConverterBoolean.write(value.`supportsWebhooks`, buf)
            FfiConverterBoolean.write(value.`supports3ds`, buf)
    }
}



data class HttpRequest (
    val `url`: kotlin.String, 
    val `method`: HttpMethod, 
    val `headers`: Map<kotlin.String, kotlin.String>, 
    val `body`: kotlin.String?, 
    val `bodyFormat`: BodyFormat
) {
    
    companion object
}

/**
 * @suppress
 */
public object FfiConverterTypeHttpRequest: FfiConverterRustBuffer<HttpRequest> {
    override fun read(buf: ByteBuffer): HttpRequest {
        return HttpRequest(
            FfiConverterString.read(buf),
            FfiConverterTypeHttpMethod.read(buf),
            FfiConverterMapStringString.read(buf),
            FfiConverterOptionalString.read(buf),
            FfiConverterTypeBodyFormat.read(buf),
        )
    }

    override fun allocationSize(value: HttpRequest) = (
            FfiConverterString.allocationSize(value.`url`) +
            FfiConverterTypeHttpMethod.allocationSize(value.`method`) +
            FfiConverterMapStringString.allocationSize(value.`headers`) +
            FfiConverterOptionalString.allocationSize(value.`body`) +
            FfiConverterTypeBodyFormat.allocationSize(value.`bodyFormat`)
    )

    override fun write(value: HttpRequest, buf: ByteBuffer) {
            FfiConverterString.write(value.`url`, buf)
            FfiConverterTypeHttpMethod.write(value.`method`, buf)
            FfiConverterMapStringString.write(value.`headers`, buf)
            FfiConverterOptionalString.write(value.`body`, buf)
            FfiConverterTypeBodyFormat.write(value.`bodyFormat`, buf)
    }
}



data class PaymentData (
    val `amount`: kotlin.Long, 
    val `currency`: kotlin.String, 
    val `paymentMethod`: PaymentMethod?, 
    val `referenceId`: kotlin.String?, 
    val `transactionId`: kotlin.String?, 
    val `returnUrl`: kotlin.String?, 
    val `metadata`: kotlin.String?
) {
    
    companion object
}

/**
 * @suppress
 */
public object FfiConverterTypePaymentData: FfiConverterRustBuffer<PaymentData> {
    override fun read(buf: ByteBuffer): PaymentData {
        return PaymentData(
            FfiConverterLong.read(buf),
            FfiConverterString.read(buf),
            FfiConverterOptionalTypePaymentMethod.read(buf),
            FfiConverterOptionalString.read(buf),
            FfiConverterOptionalString.read(buf),
            FfiConverterOptionalString.read(buf),
            FfiConverterOptionalString.read(buf),
        )
    }

    override fun allocationSize(value: PaymentData) = (
            FfiConverterLong.allocationSize(value.`amount`) +
            FfiConverterString.allocationSize(value.`currency`) +
            FfiConverterOptionalTypePaymentMethod.allocationSize(value.`paymentMethod`) +
            FfiConverterOptionalString.allocationSize(value.`referenceId`) +
            FfiConverterOptionalString.allocationSize(value.`transactionId`) +
            FfiConverterOptionalString.allocationSize(value.`returnUrl`) +
            FfiConverterOptionalString.allocationSize(value.`metadata`)
    )

    override fun write(value: PaymentData, buf: ByteBuffer) {
            FfiConverterLong.write(value.`amount`, buf)
            FfiConverterString.write(value.`currency`, buf)
            FfiConverterOptionalTypePaymentMethod.write(value.`paymentMethod`, buf)
            FfiConverterOptionalString.write(value.`referenceId`, buf)
            FfiConverterOptionalString.write(value.`transactionId`, buf)
            FfiConverterOptionalString.write(value.`returnUrl`, buf)
            FfiConverterOptionalString.write(value.`metadata`, buf)
    }
}



data class PaymentMethod (
    val `methodType`: kotlin.String, 
    val `card`: CardData?, 
    val `wallet`: WalletData?, 
    val `bankTransfer`: BankTransferData?
) {
    
    companion object
}

/**
 * @suppress
 */
public object FfiConverterTypePaymentMethod: FfiConverterRustBuffer<PaymentMethod> {
    override fun read(buf: ByteBuffer): PaymentMethod {
        return PaymentMethod(
            FfiConverterString.read(buf),
            FfiConverterOptionalTypeCardData.read(buf),
            FfiConverterOptionalTypeWalletData.read(buf),
            FfiConverterOptionalTypeBankTransferData.read(buf),
        )
    }

    override fun allocationSize(value: PaymentMethod) = (
            FfiConverterString.allocationSize(value.`methodType`) +
            FfiConverterOptionalTypeCardData.allocationSize(value.`card`) +
            FfiConverterOptionalTypeWalletData.allocationSize(value.`wallet`) +
            FfiConverterOptionalTypeBankTransferData.allocationSize(value.`bankTransfer`)
    )

    override fun write(value: PaymentMethod, buf: ByteBuffer) {
            FfiConverterString.write(value.`methodType`, buf)
            FfiConverterOptionalTypeCardData.write(value.`card`, buf)
            FfiConverterOptionalTypeWalletData.write(value.`wallet`, buf)
            FfiConverterOptionalTypeBankTransferData.write(value.`bankTransfer`, buf)
    }
}



data class PaymentResult (
    val `success`: kotlin.Boolean, 
    val `status`: PaymentStatus, 
    val `transactionId`: kotlin.String?, 
    val `connectorTransactionId`: kotlin.String?, 
    val `amount`: kotlin.Long?, 
    val `currency`: kotlin.String?, 
    val `errorCode`: kotlin.String?, 
    val `errorMessage`: kotlin.String?, 
    val `rawResponse`: kotlin.String?
) {
    
    companion object
}

/**
 * @suppress
 */
public object FfiConverterTypePaymentResult: FfiConverterRustBuffer<PaymentResult> {
    override fun read(buf: ByteBuffer): PaymentResult {
        return PaymentResult(
            FfiConverterBoolean.read(buf),
            FfiConverterTypePaymentStatus.read(buf),
            FfiConverterOptionalString.read(buf),
            FfiConverterOptionalString.read(buf),
            FfiConverterOptionalLong.read(buf),
            FfiConverterOptionalString.read(buf),
            FfiConverterOptionalString.read(buf),
            FfiConverterOptionalString.read(buf),
            FfiConverterOptionalString.read(buf),
        )
    }

    override fun allocationSize(value: PaymentResult) = (
            FfiConverterBoolean.allocationSize(value.`success`) +
            FfiConverterTypePaymentStatus.allocationSize(value.`status`) +
            FfiConverterOptionalString.allocationSize(value.`transactionId`) +
            FfiConverterOptionalString.allocationSize(value.`connectorTransactionId`) +
            FfiConverterOptionalLong.allocationSize(value.`amount`) +
            FfiConverterOptionalString.allocationSize(value.`currency`) +
            FfiConverterOptionalString.allocationSize(value.`errorCode`) +
            FfiConverterOptionalString.allocationSize(value.`errorMessage`) +
            FfiConverterOptionalString.allocationSize(value.`rawResponse`)
    )

    override fun write(value: PaymentResult, buf: ByteBuffer) {
            FfiConverterBoolean.write(value.`success`, buf)
            FfiConverterTypePaymentStatus.write(value.`status`, buf)
            FfiConverterOptionalString.write(value.`transactionId`, buf)
            FfiConverterOptionalString.write(value.`connectorTransactionId`, buf)
            FfiConverterOptionalLong.write(value.`amount`, buf)
            FfiConverterOptionalString.write(value.`currency`, buf)
            FfiConverterOptionalString.write(value.`errorCode`, buf)
            FfiConverterOptionalString.write(value.`errorMessage`, buf)
            FfiConverterOptionalString.write(value.`rawResponse`, buf)
    }
}



data class TransformRequestInput (
    val `connector`: kotlin.String, 
    val `flow`: kotlin.String, 
    val `auth`: Map<kotlin.String, kotlin.String>, 
    val `payment`: PaymentData
) {
    
    companion object
}

/**
 * @suppress
 */
public object FfiConverterTypeTransformRequestInput: FfiConverterRustBuffer<TransformRequestInput> {
    override fun read(buf: ByteBuffer): TransformRequestInput {
        return TransformRequestInput(
            FfiConverterString.read(buf),
            FfiConverterString.read(buf),
            FfiConverterMapStringString.read(buf),
            FfiConverterTypePaymentData.read(buf),
        )
    }

    override fun allocationSize(value: TransformRequestInput) = (
            FfiConverterString.allocationSize(value.`connector`) +
            FfiConverterString.allocationSize(value.`flow`) +
            FfiConverterMapStringString.allocationSize(value.`auth`) +
            FfiConverterTypePaymentData.allocationSize(value.`payment`)
    )

    override fun write(value: TransformRequestInput, buf: ByteBuffer) {
            FfiConverterString.write(value.`connector`, buf)
            FfiConverterString.write(value.`flow`, buf)
            FfiConverterMapStringString.write(value.`auth`, buf)
            FfiConverterTypePaymentData.write(value.`payment`, buf)
    }
}



data class TransformResponseInput (
    val `connector`: kotlin.String, 
    val `flow`: kotlin.String, 
    val `statusCode`: kotlin.UShort, 
    val `headers`: Map<kotlin.String, kotlin.String>, 
    val `body`: kotlin.String
) {
    
    companion object
}

/**
 * @suppress
 */
public object FfiConverterTypeTransformResponseInput: FfiConverterRustBuffer<TransformResponseInput> {
    override fun read(buf: ByteBuffer): TransformResponseInput {
        return TransformResponseInput(
            FfiConverterString.read(buf),
            FfiConverterString.read(buf),
            FfiConverterUShort.read(buf),
            FfiConverterMapStringString.read(buf),
            FfiConverterString.read(buf),
        )
    }

    override fun allocationSize(value: TransformResponseInput) = (
            FfiConverterString.allocationSize(value.`connector`) +
            FfiConverterString.allocationSize(value.`flow`) +
            FfiConverterUShort.allocationSize(value.`statusCode`) +
            FfiConverterMapStringString.allocationSize(value.`headers`) +
            FfiConverterString.allocationSize(value.`body`)
    )

    override fun write(value: TransformResponseInput, buf: ByteBuffer) {
            FfiConverterString.write(value.`connector`, buf)
            FfiConverterString.write(value.`flow`, buf)
            FfiConverterUShort.write(value.`statusCode`, buf)
            FfiConverterMapStringString.write(value.`headers`, buf)
            FfiConverterString.write(value.`body`, buf)
    }
}



data class WalletData (
    val `walletType`: kotlin.String, 
    val `token`: kotlin.String?, 
    val `email`: kotlin.String?
) {
    
    companion object
}

/**
 * @suppress
 */
public object FfiConverterTypeWalletData: FfiConverterRustBuffer<WalletData> {
    override fun read(buf: ByteBuffer): WalletData {
        return WalletData(
            FfiConverterString.read(buf),
            FfiConverterOptionalString.read(buf),
            FfiConverterOptionalString.read(buf),
        )
    }

    override fun allocationSize(value: WalletData) = (
            FfiConverterString.allocationSize(value.`walletType`) +
            FfiConverterOptionalString.allocationSize(value.`token`) +
            FfiConverterOptionalString.allocationSize(value.`email`)
    )

    override fun write(value: WalletData, buf: ByteBuffer) {
            FfiConverterString.write(value.`walletType`, buf)
            FfiConverterOptionalString.write(value.`token`, buf)
            FfiConverterOptionalString.write(value.`email`, buf)
    }
}




enum class AuthType {
    
    HEADER_KEY,
    BASIC_AUTH,
    BODY_KEY,
    SIGNATURE_KEY,
    MULTI_AUTH_KEY,
    CERTIFICATE_AUTH,
    NO_KEY;
    companion object
}


/**
 * @suppress
 */
public object FfiConverterTypeAuthType: FfiConverterRustBuffer<AuthType> {
    override fun read(buf: ByteBuffer) = try {
        AuthType.values()[buf.getInt() - 1]
    } catch (e: IndexOutOfBoundsException) {
        throw RuntimeException("invalid enum value, something is very wrong!!", e)
    }

    override fun allocationSize(value: AuthType) = 4UL

    override fun write(value: AuthType, buf: ByteBuffer) {
        buf.putInt(value.ordinal + 1)
    }
}






enum class BodyFormat {
    
    JSON,
    FORM_URL_ENCODED,
    XML,
    RAW;
    companion object
}


/**
 * @suppress
 */
public object FfiConverterTypeBodyFormat: FfiConverterRustBuffer<BodyFormat> {
    override fun read(buf: ByteBuffer) = try {
        BodyFormat.values()[buf.getInt() - 1]
    } catch (e: IndexOutOfBoundsException) {
        throw RuntimeException("invalid enum value, something is very wrong!!", e)
    }

    override fun allocationSize(value: BodyFormat) = 4UL

    override fun write(value: BodyFormat, buf: ByteBuffer) {
        buf.putInt(value.ordinal + 1)
    }
}







sealed class ConnectorException(message: String): kotlin.Exception(message) {
        
        class UnknownConnector(message: String) : ConnectorException(message)
        
        class UnsupportedFlow(message: String) : ConnectorException(message)
        
        class MissingAuthField(message: String) : ConnectorException(message)
        
        class MissingPaymentField(message: String) : ConnectorException(message)
        
        class TransformException(message: String) : ConnectorException(message)
        
        class ParseException(message: String) : ConnectorException(message)
        
        class InvalidInput(message: String) : ConnectorException(message)
        

    companion object ErrorHandler : UniffiRustCallStatusErrorHandler<ConnectorException> {
        override fun lift(error_buf: RustBuffer.ByValue): ConnectorException = FfiConverterTypeConnectorError.lift(error_buf)
    }
}

/**
 * @suppress
 */
public object FfiConverterTypeConnectorError : FfiConverterRustBuffer<ConnectorException> {
    override fun read(buf: ByteBuffer): ConnectorException {
        
            return when(buf.getInt()) {
            1 -> ConnectorException.UnknownConnector(FfiConverterString.read(buf))
            2 -> ConnectorException.UnsupportedFlow(FfiConverterString.read(buf))
            3 -> ConnectorException.MissingAuthField(FfiConverterString.read(buf))
            4 -> ConnectorException.MissingPaymentField(FfiConverterString.read(buf))
            5 -> ConnectorException.TransformException(FfiConverterString.read(buf))
            6 -> ConnectorException.ParseException(FfiConverterString.read(buf))
            7 -> ConnectorException.InvalidInput(FfiConverterString.read(buf))
            else -> throw RuntimeException("invalid error enum value, something is very wrong!!")
        }
        
    }

    override fun allocationSize(value: ConnectorException): ULong {
        return 4UL
    }

    override fun write(value: ConnectorException, buf: ByteBuffer) {
        when(value) {
            is ConnectorException.UnknownConnector -> {
                buf.putInt(1)
                Unit
            }
            is ConnectorException.UnsupportedFlow -> {
                buf.putInt(2)
                Unit
            }
            is ConnectorException.MissingAuthField -> {
                buf.putInt(3)
                Unit
            }
            is ConnectorException.MissingPaymentField -> {
                buf.putInt(4)
                Unit
            }
            is ConnectorException.TransformException -> {
                buf.putInt(5)
                Unit
            }
            is ConnectorException.ParseException -> {
                buf.putInt(6)
                Unit
            }
            is ConnectorException.InvalidInput -> {
                buf.putInt(7)
                Unit
            }
        }.let { /* this makes the `when` an expression, which ensures it is exhaustive */ }
    }

}




enum class HttpMethod {
    
    GET,
    POST,
    PUT,
    DELETE,
    PATCH;
    companion object
}


/**
 * @suppress
 */
public object FfiConverterTypeHttpMethod: FfiConverterRustBuffer<HttpMethod> {
    override fun read(buf: ByteBuffer) = try {
        HttpMethod.values()[buf.getInt() - 1]
    } catch (e: IndexOutOfBoundsException) {
        throw RuntimeException("invalid enum value, something is very wrong!!", e)
    }

    override fun allocationSize(value: HttpMethod) = 4UL

    override fun write(value: HttpMethod, buf: ByteBuffer) {
        buf.putInt(value.ordinal + 1)
    }
}






enum class PaymentFlow {
    
    AUTHORIZE,
    CAPTURE,
    VOID,
    REFUND,
    SYNC,
    SETUP_MANDATE;
    companion object
}


/**
 * @suppress
 */
public object FfiConverterTypePaymentFlow: FfiConverterRustBuffer<PaymentFlow> {
    override fun read(buf: ByteBuffer) = try {
        PaymentFlow.values()[buf.getInt() - 1]
    } catch (e: IndexOutOfBoundsException) {
        throw RuntimeException("invalid enum value, something is very wrong!!", e)
    }

    override fun allocationSize(value: PaymentFlow) = 4UL

    override fun write(value: PaymentFlow, buf: ByteBuffer) {
        buf.putInt(value.ordinal + 1)
    }
}






enum class PaymentStatus {
    
    SUCCEEDED,
    AUTHORIZED,
    PENDING,
    FAILED,
    CANCELLED,
    REQUIRES_ACTION,
    PROCESSING,
    UNKNOWN;
    companion object
}


/**
 * @suppress
 */
public object FfiConverterTypePaymentStatus: FfiConverterRustBuffer<PaymentStatus> {
    override fun read(buf: ByteBuffer) = try {
        PaymentStatus.values()[buf.getInt() - 1]
    } catch (e: IndexOutOfBoundsException) {
        throw RuntimeException("invalid enum value, something is very wrong!!", e)
    }

    override fun allocationSize(value: PaymentStatus) = 4UL

    override fun write(value: PaymentStatus, buf: ByteBuffer) {
        buf.putInt(value.ordinal + 1)
    }
}






/**
 * @suppress
 */
public object FfiConverterOptionalLong: FfiConverterRustBuffer<kotlin.Long?> {
    override fun read(buf: ByteBuffer): kotlin.Long? {
        if (buf.get().toInt() == 0) {
            return null
        }
        return FfiConverterLong.read(buf)
    }

    override fun allocationSize(value: kotlin.Long?): ULong {
        if (value == null) {
            return 1UL
        } else {
            return 1UL + FfiConverterLong.allocationSize(value)
        }
    }

    override fun write(value: kotlin.Long?, buf: ByteBuffer) {
        if (value == null) {
            buf.put(0)
        } else {
            buf.put(1)
            FfiConverterLong.write(value, buf)
        }
    }
}




/**
 * @suppress
 */
public object FfiConverterOptionalString: FfiConverterRustBuffer<kotlin.String?> {
    override fun read(buf: ByteBuffer): kotlin.String? {
        if (buf.get().toInt() == 0) {
            return null
        }
        return FfiConverterString.read(buf)
    }

    override fun allocationSize(value: kotlin.String?): ULong {
        if (value == null) {
            return 1UL
        } else {
            return 1UL + FfiConverterString.allocationSize(value)
        }
    }

    override fun write(value: kotlin.String?, buf: ByteBuffer) {
        if (value == null) {
            buf.put(0)
        } else {
            buf.put(1)
            FfiConverterString.write(value, buf)
        }
    }
}




/**
 * @suppress
 */
public object FfiConverterOptionalTypeBankTransferData: FfiConverterRustBuffer<BankTransferData?> {
    override fun read(buf: ByteBuffer): BankTransferData? {
        if (buf.get().toInt() == 0) {
            return null
        }
        return FfiConverterTypeBankTransferData.read(buf)
    }

    override fun allocationSize(value: BankTransferData?): ULong {
        if (value == null) {
            return 1UL
        } else {
            return 1UL + FfiConverterTypeBankTransferData.allocationSize(value)
        }
    }

    override fun write(value: BankTransferData?, buf: ByteBuffer) {
        if (value == null) {
            buf.put(0)
        } else {
            buf.put(1)
            FfiConverterTypeBankTransferData.write(value, buf)
        }
    }
}




/**
 * @suppress
 */
public object FfiConverterOptionalTypeCardData: FfiConverterRustBuffer<CardData?> {
    override fun read(buf: ByteBuffer): CardData? {
        if (buf.get().toInt() == 0) {
            return null
        }
        return FfiConverterTypeCardData.read(buf)
    }

    override fun allocationSize(value: CardData?): ULong {
        if (value == null) {
            return 1UL
        } else {
            return 1UL + FfiConverterTypeCardData.allocationSize(value)
        }
    }

    override fun write(value: CardData?, buf: ByteBuffer) {
        if (value == null) {
            buf.put(0)
        } else {
            buf.put(1)
            FfiConverterTypeCardData.write(value, buf)
        }
    }
}




/**
 * @suppress
 */
public object FfiConverterOptionalTypeConnectorInfo: FfiConverterRustBuffer<ConnectorInfo?> {
    override fun read(buf: ByteBuffer): ConnectorInfo? {
        if (buf.get().toInt() == 0) {
            return null
        }
        return FfiConverterTypeConnectorInfo.read(buf)
    }

    override fun allocationSize(value: ConnectorInfo?): ULong {
        if (value == null) {
            return 1UL
        } else {
            return 1UL + FfiConverterTypeConnectorInfo.allocationSize(value)
        }
    }

    override fun write(value: ConnectorInfo?, buf: ByteBuffer) {
        if (value == null) {
            buf.put(0)
        } else {
            buf.put(1)
            FfiConverterTypeConnectorInfo.write(value, buf)
        }
    }
}




/**
 * @suppress
 */
public object FfiConverterOptionalTypePaymentMethod: FfiConverterRustBuffer<PaymentMethod?> {
    override fun read(buf: ByteBuffer): PaymentMethod? {
        if (buf.get().toInt() == 0) {
            return null
        }
        return FfiConverterTypePaymentMethod.read(buf)
    }

    override fun allocationSize(value: PaymentMethod?): ULong {
        if (value == null) {
            return 1UL
        } else {
            return 1UL + FfiConverterTypePaymentMethod.allocationSize(value)
        }
    }

    override fun write(value: PaymentMethod?, buf: ByteBuffer) {
        if (value == null) {
            buf.put(0)
        } else {
            buf.put(1)
            FfiConverterTypePaymentMethod.write(value, buf)
        }
    }
}




/**
 * @suppress
 */
public object FfiConverterOptionalTypeWalletData: FfiConverterRustBuffer<WalletData?> {
    override fun read(buf: ByteBuffer): WalletData? {
        if (buf.get().toInt() == 0) {
            return null
        }
        return FfiConverterTypeWalletData.read(buf)
    }

    override fun allocationSize(value: WalletData?): ULong {
        if (value == null) {
            return 1UL
        } else {
            return 1UL + FfiConverterTypeWalletData.allocationSize(value)
        }
    }

    override fun write(value: WalletData?, buf: ByteBuffer) {
        if (value == null) {
            buf.put(0)
        } else {
            buf.put(1)
            FfiConverterTypeWalletData.write(value, buf)
        }
    }
}




/**
 * @suppress
 */
public object FfiConverterSequenceString: FfiConverterRustBuffer<List<kotlin.String>> {
    override fun read(buf: ByteBuffer): List<kotlin.String> {
        val len = buf.getInt()
        return List<kotlin.String>(len) {
            FfiConverterString.read(buf)
        }
    }

    override fun allocationSize(value: List<kotlin.String>): ULong {
        val sizeForLength = 4UL
        val sizeForItems = value.map { FfiConverterString.allocationSize(it) }.sum()
        return sizeForLength + sizeForItems
    }

    override fun write(value: List<kotlin.String>, buf: ByteBuffer) {
        buf.putInt(value.size)
        value.iterator().forEach {
            FfiConverterString.write(it, buf)
        }
    }
}




/**
 * @suppress
 */
public object FfiConverterSequenceTypePaymentFlow: FfiConverterRustBuffer<List<PaymentFlow>> {
    override fun read(buf: ByteBuffer): List<PaymentFlow> {
        val len = buf.getInt()
        return List<PaymentFlow>(len) {
            FfiConverterTypePaymentFlow.read(buf)
        }
    }

    override fun allocationSize(value: List<PaymentFlow>): ULong {
        val sizeForLength = 4UL
        val sizeForItems = value.map { FfiConverterTypePaymentFlow.allocationSize(it) }.sum()
        return sizeForLength + sizeForItems
    }

    override fun write(value: List<PaymentFlow>, buf: ByteBuffer) {
        buf.putInt(value.size)
        value.iterator().forEach {
            FfiConverterTypePaymentFlow.write(it, buf)
        }
    }
}




/**
 * @suppress
 */
public object FfiConverterMapStringString: FfiConverterRustBuffer<Map<kotlin.String, kotlin.String>> {
    override fun read(buf: ByteBuffer): Map<kotlin.String, kotlin.String> {
        val len = buf.getInt()
        return buildMap<kotlin.String, kotlin.String>(len) {
            repeat(len) {
                val k = FfiConverterString.read(buf)
                val v = FfiConverterString.read(buf)
                this[k] = v
            }
        }
    }

    override fun allocationSize(value: Map<kotlin.String, kotlin.String>): ULong {
        val spaceForMapSize = 4UL
        val spaceForChildren = value.map { (k, v) ->
            FfiConverterString.allocationSize(k) +
            FfiConverterString.allocationSize(v)
        }.sum()
        return spaceForMapSize + spaceForChildren
    }

    override fun write(value: Map<kotlin.String, kotlin.String>, buf: ByteBuffer) {
        buf.putInt(value.size)
        // The parens on `(k, v)` here ensure we're calling the right method,
        // which is important for compatibility with older android devices.
        // Ref https://blog.danlew.net/2017/03/16/kotlin-puzzler-whose-line-is-it-anyways/
        value.forEach { (k, v) ->
            FfiConverterString.write(k, buf)
            FfiConverterString.write(v, buf)
        }
    }
} fun `createCardPaymentMethod`(`number`: kotlin.String, `expMonth`: kotlin.UInt, `expYear`: kotlin.UInt, `cvc`: kotlin.String, `holderName`: kotlin.String?): PaymentMethod {
            return FfiConverterTypePaymentMethod.lift(
    uniffiRustCall() { _status ->
    UniffiLib.INSTANCE.uniffi_connector_ffi_uniffi_fn_func_create_card_payment_method(
        FfiConverterString.lower(`number`),FfiConverterUInt.lower(`expMonth`),FfiConverterUInt.lower(`expYear`),FfiConverterString.lower(`cvc`),FfiConverterOptionalString.lower(`holderName`),_status)
}
    )
    }
    
 fun `createWalletPaymentMethod`(`walletType`: kotlin.String, `token`: kotlin.String?, `email`: kotlin.String?): PaymentMethod {
            return FfiConverterTypePaymentMethod.lift(
    uniffiRustCall() { _status ->
    UniffiLib.INSTANCE.uniffi_connector_ffi_uniffi_fn_func_create_wallet_payment_method(
        FfiConverterString.lower(`walletType`),FfiConverterOptionalString.lower(`token`),FfiConverterOptionalString.lower(`email`),_status)
}
    )
    }
    
 fun `getConnectorInfo`(`name`: kotlin.String): ConnectorInfo? {
            return FfiConverterOptionalTypeConnectorInfo.lift(
    uniffiRustCall() { _status ->
    UniffiLib.INSTANCE.uniffi_connector_ffi_uniffi_fn_func_get_connector_info(
        FfiConverterString.lower(`name`),_status)
}
    )
    }
    
 fun `listSupportedConnectors`(): List<kotlin.String> {
            return FfiConverterSequenceString.lift(
    uniffiRustCall() { _status ->
    UniffiLib.INSTANCE.uniffi_connector_ffi_uniffi_fn_func_list_supported_connectors(
        _status)
}
    )
    }
    

    @Throws(ConnectorException::class) fun `transformRequest`(`input`: TransformRequestInput): HttpRequest {
            return FfiConverterTypeHttpRequest.lift(
    uniffiRustCallWithError(ConnectorException) { _status ->
    UniffiLib.INSTANCE.uniffi_connector_ffi_uniffi_fn_func_transform_request(
        FfiConverterTypeTransformRequestInput.lower(`input`),_status)
}
    )
    }
    

    @Throws(ConnectorException::class) fun `transformResponse`(`input`: TransformResponseInput): PaymentResult {
            return FfiConverterTypePaymentResult.lift(
    uniffiRustCallWithError(ConnectorException) { _status ->
    UniffiLib.INSTANCE.uniffi_connector_ffi_uniffi_fn_func_transform_response(
        FfiConverterTypeTransformResponseInput.lower(`input`),_status)
}
    )
    }
    


